<<<<<<< HEAD


	// [FILLER]
	new Struct("mi seh", 2, FILLER, "")
	new Struct("a mi seh", 2, FILLER, "")
	new Struct("boom", 1, FILLER, "")
	new Struct("oom", 1, FILLER, "")
	new Struct("Lord have mercy", 2, FILLER, "")
	new Struct("sekkle", 2, FILLER, "")
	new Struct("man come", 2, FILLER, "")
	new Struct("watch out", 2, FILLER, "")
	new Struct("cause", 1, FILLER, "")
	new Struct("cah", 1, FILLER, "")
	new Struct("nuh mean", 2, FILLER, "")
	new Struct("mi tell you", 2, FILLER, "")
	new Struct("hear me", 2, FILLER, "")
	new Struct("man", 1, FILLER, "")
	new Struct("live it up", 3, FILLER, "")

	// [PRON]
	new Struct("we", 1, PRON, "i")
	new Struct("we all", 1, PRON, "al")
	new Struct("mi", 1, PRON, "i")
	new Struct("mi", 1, PRON, "i")
	new Struct("mi", 1, PRON, "i")
	new Struct("I", 1, PRON, "ai")
	new Struct("I and I", 1, PRON, "ai")
	new Struct("rastafari", 4, PRON, "ai")
	new Struct("unu", 1, PRON, "u")
	new Struct("dem", 1, PRON, "em")
	new Struct("dem", 1, PRON, "em")
	new Struct("dem", 1, PRON, "em")
	new Struct("she", 1, PRON, "i")
	new Struct("him", 1, PRON, "im")
	new Struct("it", 1, PRON, "it")
	new Struct("man", 1, PRON, "it")
	new Struct("I man", 1, PRON, "it")

	// [PREADJ]
	new Struct("ya", 1, PREADJ, "")
	new Struct("mi", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("de", 1, PREADJ, "")
	new Struct("da", 1, PREADJ, "")
	new Struct("another", 2, PREADJ, "")
	new Struct("every", 3, PREADJ, "")
	new Struct("a", 1, PREADJ, "")
	new Struct("some", 1, PREADJ, "")
	new Struct("one", 1, PREADJ, "")

	// [POSTADJ]
	new Struct("dead", 1, POSTADJ, "ed")
	new Struct("good", 1, POSTADJ, "ud")
	new Struct("hot", 1, POSTADJ, "at")
	new Struct("high", 1, POSTADJ, "ai")
	new Struct("wise", 1, POSTADJ, "ais")
	new Struct("mean", 1, POSTADJ, "in")
	new Struct("green", 1, POSTADJ, "in")
	new Struct("clean", 1, POSTADJ, "in")
	new Struct("unseen", 1, POSTADJ, "in")
	new Struct("mad", 1, POSTADJ, "ad")
	new Struct("strong", 1, POSTADJ, "ad")
	new Struct("alright", 2, POSTADJ, "ait")
	new Struct("original", 4, POSTADJ, "al")
	new Struct("crucial", 2, POSTADJ, "al")
	new Struct("tall", 1, POSTADJ, "al")

	// [PREP]
	new Struct("for", 1, PREP, "")
	new Struct("like", 1, PREP, "")

	// [LOCPREP]
	new Struct("inna", 1, LOCPREP, "")
	new Struct("a", 1, LOCPREP, "")
	new Struct("back inna", 2, LOCPREP, "")
	new Struct("in", 1, LOCPREP, "")
	new Struct("from", 1, LOCPREP, "")
	new Struct("round", 1, LOCPREP, "")
	new Struct("back to", 2, LOCPREP, "")
	new Struct("back a", 2, LOCPREP, "")
	new Struct("outta", 2, LOCPREP, "")
	new Struct("straight outta", 3, LOCPREP, "")

	// [LOCATION]
	new Struct("Jamaica", 3, LOC, "ca")
	new Struct("Jamdong", 2, LOC, "own")
	new Struct("Kingston", 2, LOC, "own")
	new Struct("yard", 1, LOC, "ad")
	new Struct("Orange Hill", 3, LOC, "il")
	new Struct("Saint Anne", 2, LOC, "an")
	new Struct("Holy Land", 3, LOC, "an")
	new Struct("London", 2, LOC, "an")
	new Struct("Amstadam", 3, LOC, "an")
	new Struct("Carrabian", 3, LOC, "an")
	new Struct("England", 2, LOC, "an")
	new Struct("Promised Land", 3, LOC, "an")
	new Struct("di system", 3, LOC, "em")
	new Struct("Great Britain", 2, LOC, "em")
	new Struct("mama Africa", 5, LOC, "ca")
	new Struct("God's acre", 3, LOC, "ca")
	new Struct("Mount Zion", 3, LOC, "an")
	new Struct("Angola", 3, LOC, "la")
	new Struct("town", 3, LOC, "on")
	new Struct("Brooklyn", 2, LOC, "in")


	// [TIME]
	new Struct("last night", 2, TIME, "ait")
	new Struct("today", 2, TIME, "ei")
	new Struct("inna di morning", 4, TIME, "in")
	new Struct("pon de place", 3, TIME, "es")
	new Struct("inna whim", 3, TIME, "im")

	// [VERB]
	new Struct("ring", 1, VERB, "in")
	new Struct("sing", 1, VERB, "in")
	new Struct("fling", 1, VERB, "in")
	new Struct("repeat", 2, VERB, "it")
	new Struct("spit", 1, VERB, "it")
	new Struct("play", 1, VERB, "ei")
	new Struct("say", 1, VERB, "ei")
	new Struct("pray", 1, VERB, "ei")
	new Struct("gray", 1, VERB, "ei")
	new Struct("come", 1, VERB, "om")
	new Struct("overcome", 3, VERB, "om")
	new Struct("bun", 1, VERB, "om")
	new Struct("bless up", 2, VERB, "op")
	new Struct("bun up", 2, VERB, "op")
	new Struct("blaze up", 2, VERB, "op")
	new Struct("stop", 1, VERB, "op")
	new Struct("pressure", 2, VERB, "ja")
	new Struct("think", 1, VERB, "in")
	new Struct("see", 1, VERB, "i")
	new Struct("try", 1, VERB, "ai")
	new Struct("tremble", 2, VERB, "el")
	new Struct("wrestle", 2, VERB, "el")
	new Struct("meddle", 2, VERB, "el")
	new Struct("sekkle", 2, VERB, "el")
	new Struct("revel", 2, VERB, "el")
	new Struct("struggle", 2, VERB, "el")
	new Struct("assemble", 3, VERB, "el")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("jump", 1, VERB, "")
	new Struct("drop", 1, VERB, "")
	new Struct("know", 1, VERB, "own")
	new Struct("digress", 2, VERB, "es")
	new Struct("impress", 2, VERB, "es")
	new Struct("bless", 1, VERB, "es")
	new Struct("rise", 1, VERB, "ais")
	new Struct("empathize", 3, VERB, "ais")
	new Struct("setup", 2, VERB, "eta")
	new Struct("take", 1, VERB, "ek")
	new Struct("shake", 1, VERB, "ek")
	new Struct("beg", 1, VERB, "ek")
	new Struct("make", 3, VERB, "ek")
	new Struct("let go pon", 3, VERB, "an")
	new Struct("awaken", 3, VERB, "ca")
	new Struct("fall", 1, VERB, "al")
	new Struct("ball", 1, VERB, "al")

	// [XPR] [VERBEXPR]
	new Struct("smoke di weed", 3, VERBXPR, "id")
	new Struct("smoke di herb", 3, VERBXPR, "erb")
	new Struct("eyes turn red", 3, VERBXPR, "ed")
	new Struct("see it through", 3, VERBXPR, "u")
	new Struct("take a break", 3, VERBXPR, "ek")
	new Struct("do something wrong", 5, VERBXPR, "on")
	new Struct("will be alright", 5, VERBXPR, "on")
	new Struct("do betta", 3, VERBXPR, "eta")
	new Struct("digress", 2, VERBXPR, "es")
	new Struct("guess", 1, VERBXPR, "es")
	new Struct("stress", 1, VERBXPR, "es")
	new Struct("dress ", 1, VERBXPR, "es")

	// [PREF] [VERBPREF]
	new Struct("smoke", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("blaze up", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("bubble", 2, VERBPREF, "", [], SMOKABLE)
	new Struct("get", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("roll up", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("smuggle", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("bake", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("draw", 1, VERBPREF, "", [], SMOKABLE)

	new Struct("aknowledge", 3, VERBPREF, "ij", [], CONCEPT)
	new Struct("achieve", 2, VERBPREF, "iv", [], CONCEPT)
	new Struct("give out", 2, VERBPREF, "out", [], CONCEPT)
	new Struct("learn about", 1, VERBPREF, "out", [], CONCEPT)
	new Struct("have", 2, VERBPREF, "av", [], CONCEPT)
	new Struct("praise", 1, VERBPREF, "es", [], CONCEPT)
	new Struct("spread", 1, VERBPREF, "ed", [], CONCEPT)
	new Struct("sekkle pon", 1, VERBPREF, "on", [], CONCEPT)
	new Struct("prolong", 1, VERBPREF, "on", [], CONCEPT)
	new Struct("bless", 1, VERBPREF, "es", [], CONCEPT)
	new Struct("express", 2, VERBPREF, "es", [], CONCEPT)
	new Struct("confess", 2, VERBPREF, "es", [], CONCEPT)
	new Struct("address", 2, VERBPREF, "es", [], CONCEPT)

	new Struct("talk to", 2, VERBPREF, "u", [], PERSON)
	new Struct("listen to", 3, VERBPREF, "u", [], PERSON)
	new Struct("be like", 2, VERBPREF, "u", [], PERSON)
	new Struct("turn in", 2, VERBPREF, "in", [], PERSON)
	new Struct("praise", 2, VERBPREF, "es", [], PERSON)
	new Struct("praise", 2, VERBPREF, "es", [], PERSON)
	new Struct("impress", 3, VERBPREF, "es", [], PERSON)
	new Struct("brutalize", 3, VERBPREF, "ize", [], PERSON)

	//new Struct("shoot", 3, VERBPREF, "ut", [], MUSIC)

	// [MODALVERB]
	new Struct("want fi", 1, 		MODALVERB, "", [])
	new Struct("can", 1, 			MODALVERB, "", [])
	new Struct("affi", 2, 			MODALVERB, "", [])
	new Struct("nuh go", 2, 		MODALVERB, "", [])
	new Struct("a go", 2, 			MODALVERB, "", [])
	new Struct("like", 1, 			MODALVERB, "", ["to", "fi"])
	new Struct("let", 1, 			MODALVERB, "", [PRON])
	new Struct("neva", 2, 			MODALVERB, "", [])
	new Struct("neva eva", 3,		MODALVERB, "", [])
	new Struct("done", 1,			MODALVERB, "", [])
	new Struct("see dat", 2,		MODALVERB, "", [PRON, PERSON])
	new Struct("make sure dat", 3,	MODALVERB, "", [PRON, PERSON])
	new Struct("said", 1, 			MODALVERB, "", [PRON, PERSON])
	new Struct("shall", 1, 			MODALVERB, "", [])
	new Struct("will have to", 2, 	MODALVERB, "", [])
	new Struct("make", 1, 			MODALVERB, "", [PRON])

	// [ADV]
	new Struct("away", 1, ADV, "ei")
	new Struct("ahead", 2, ADV, "ed")
	new Struct("to di top", 3, ADV, "op")
	new Struct("again", 2, ADV, "em")
	new Struct("down", 1, ADV, "own")
	new Struct("over", 2, ADV, "va")
	new Struct("hard", 2, ADV, "ad")
	new Struct("wrong", 2, ADV, "on")

	// [SMOKABLE]
	new Struct("weed", 1, SMOKABLE, "id")
	new Struct("ganja", 2, SMOKABLE, "ja")
	new Struct("sensi", 2, SMOKABLE, "si")
	new Struct("herb", 1, SMOKABLE, "erb")
	new Struct("bong", 1, SMOKABLE, "on")
	new Struct("sensimilia", 4, SMOKABLE, "ia")
	new Struct("sess", 1, SMOKABLE, "es")
	new Struct("spliff", 1, SMOKABLE, "if")
	new Struct("bud", 1, SMOKABLE, "od")
	new Struct("grass", 1, SMOKABLE, "as")
	new Struct("green", 1, SMOKABLE, "in")
	new Struct("sweet Mary Jane", 4, SMOKABLE, "ein")
	new Struct("Mary Jane", 3, SMOKABLE, "ein")
	new Struct("marijuana", 4, SMOKABLE, "ana")
	new Struct("cana", 2, SMOKABLE, "ana")
	new Struct("pot", 1, SMOKABLE, "at")
	new Struct("420", 3, SMOKABLE, "ti")
	new Struct("blunt", 1, SMOKABLE, "on")
	new Struct("chronic", 2, SMOKABLE, "ic")
	new Struct("fyah", 2, SMOKABLE, "ia")
	new Struct("cali", 2, SMOKABLE, "li")

	// Achieve, give out, praise, spread, sekkle
	new Struct("highest grade", 3, CONCEPT, "ed")
	new Struct("mayhem", 2, CONCEPT, "em")
	new Struct("big man thing", 1, CONCEPT, "in")
	new Struct("thing", 1, CONCEPT, "in")
	new Struct("sound", 1, CONCEPT, "own")
	new Struct("jah", 1, CONCEPT, "ja")
	new Struct("jahjah", 2, CONCEPT, "ja")
	new Struct("ganja", 2, CONCEPT, "ja")
	new Struct("culture", 2, CONCEPT, "ja")
	new Struct("dispute", 2, CONCEPT, "ut")
	new Struct("stress", 1, CONCEPT, "es")
	new Struct("happiness", 3, CONCEPT, "es")
	new Struct("rightousness", 3, CONCEPT, "es")
	new Struct("distress", 2, CONCEPT, "es")
	new Struct("finest", 2, CONCEPT, "es")
	new Struct("vibration", 4, CONCEPT, "an")
	new Struct("elevation", 4, CONCEPT, "an")
	new Struct("liberation", 4, CONCEPT, "an")
	new Struct("function", 2, CONCEPT, "an")
	new Struct("redemption", 3, CONCEPT, "an")
	new Struct("destruction", 3, CONCEPT, "an")
	new Struct("seduction", 3, CONCEPT, "an")
	new Struct("introduction", 3, CONCEPT, "an")
	new Struct("truth", 1, CONCEPT, "ut")
	new Struct("new heights", 2, CONCEPT, "ait")
	new Struct("light", 1, CONCEPT, "ait")
	new Struct("love", 1, CONCEPT, "av")
	new Struct("meditation", 4, CONCEPT, "an")
	new Struct("inspiration", 4, CONCEPT, "an")


	// [THING]
	new Struct("rasta", 2, THING, "")
	new Struct("pasta", 2, THING, "")
	new Struct("microphone", 3, THING, "own")
	new Struct("chalice", 3, THING, "is")
	new Struct("block", 1, THING, "ak")
	new Struct("head", 1, THING, "ed")
	new Struct("head", 1, THING, "ed")
	new Struct("bed", 1, THING, "ed")
	new Struct("highest grade", 3, THING, "ed")
	new Struct("bredda", 2, THING, "ed")
	new Struct("rhyme", 1, THING, "ai")
	new Struct("crime", 1, THING, "ai")
	new Struct("dime", 1, THING, "ai")
	new Struct("rude bway", 2, THING, "ai")
	new Struct("bad bway", 2, THING, "ai")
	new Struct("mankind", 2, THING, "ai")
	new Struct("selecta", 3, THING, "ca")
	new Struct("dem", 1, THING, "em")
	new Struct("anthem", 2, THING, "em")
	new Struct("whola dem", 3, THING, "em")
	new Struct("system", 2, THING, "em")
	new Struct("sound system", 3, THING, "em")
	new Struct("dis", 1, THING, "is")
	new Struct("it", 1, THING, "it")
	new Struct("weed", 1, THING, "it")
	new Struct("sound", 1, THING, "own")
	new Struct("song", 1, THING, "own")
	new Struct("song", 1, THING, "on")
	new Struct("crown", 1, THING, "own")
	new Struct("town", 1, THING, "own")
	new Struct("Kingston", 2, THING, "own")
	new Struct("babylon", 2, THING, "own")
	new Struct("two stone", 2, THING, "own")
	new Struct("DJ", 2, THING, "ei")
	new Struct("soldier", 2, THING, "ja")
	new Struct("jah", 1, THING, "ja")
	new Struct("jahjah", 2, THING, "ja")
	new Struct("ganja", 2, THING, "ja")
	new Struct("culture", 2, THING, "ja")
	new Struct("cover", 2, THING, "ova")
	new Struct("rebel", 2, THING, "el")
	new Struct("pebble", 2, THING, "el")
	new Struct("medal", 2, THING, "el")
	new Struct("metal", 2, THING, "el")
	new Struct("pedal", 2, THING, "el")
	new Struct("level", 2, THING, "el")
	new Struct("devil", 2, THING, "el")
	new Struct("vegetable", 4, THING, "el")
	new Struct("table", 2, THING, "el")
	new Struct("dat", 1, THING, "at")
	new Struct("youth", 1, THING, "ut")
	new Struct("roots", 1, THING, "ut")
	new Struct("route", 1, THING, "ut")
	new Struct("suit", 1, THING, "ut")
	new Struct("booth", 1, THING, "ut")
	new Struct("reggae roots", 3, THING, "ut")
	new Struct("house", 1, THING, "ous")
	new Struct("mouse", 1, THING, "ous")
	new Struct("speaker", 2, THING, "ika")
	new Struct("man", 1, THING, "an")
	new Struct("woman", 2, THING, "an")
	new Struct("bataclan", 3, THING, "an")
	new Struct("congress", 2, THING, "e")
	new Struct("disgrace", 2, THING, "es")
	new Struct("address", 2, THING, "es")
	new Struct("regrets", 2, THING, "es")
	new Struct("progress", 2, THING, "es")
	new Struct("place", 2, THING, "es")
	new Struct("medication", 4, THING, "an")
	new Struct("patient", 2, THING, "an")
	new Struct("cultivation", 4, THING, "an")
	new Struct("surprise", 2, THING, "ais")
	new Struct("riddim", 2, THING, "im")
	new Struct("m16", 3, THING, "im")
	new Struct("scheme", 1, THING, "im")
	new Struct("scene", 1, THING, "in")
	new Struct("queen", 1, THING, "in")
	new Struct("caffeine", 2, THING, "in")
	new Struct("eighteen", 2, THING, "in")
	new Struct("hygine", 2, THING, "in")
	new Struct("washing machine", 4, THING, "in")
	new Struct("protein", 2, THING, "in")
	new Struct("Wolverine", 3, THING, "in")
	new Struct("figurine", 3, THING, "in")
	new Struct("green", 1, THING, "in")
	new Struct("backfoot", 2, THING, "ut")
	new Struct("chain breaka", 3, THING, "ca")
	new Struct("Maker", 2, THING, "ca")
	new Struct("care taker", 3, THING, "ca")




	// And [PERSON], all are also considered THIGNS
	new Struct("selecta", 3, PERSON, "ta", [PRON, POSTADJ])
	new Struct("bredda", 2, PERSON, "ed", [PRON, POSTADJ])
	new Struct("bredren", 2, PERSON, "em", [PRON])
	new Struct("dem", 1, PERSON, "em")
	new Struct("whola dem", 3, PERSON, "em")
	new Struct("di whola dem", 3, PERSON, "em")
	new Struct("system", 3, PERSON, "em")
	new Struct("gyal dem", 2, PERSON, "em")
	new Struct("it", 1, PERSON, "it")
	new Struct("DJ", 2, PERSON, "ei", [PRON, POSTADJ])
	new Struct("soldier", 2, PERSON, "ja", [PRON, POSTADJ])
	new Struct("jah", 1, PERSON, "ja")
	new Struct("jahjah", 2, PERSON, "ja")
	new Struct("almighty Jah", 3, PERSON, "ja")
	new Struct("rebel", 2, PERSON, "el", [PRON, POSTADJ])
	new Struct("devil", 2, PERSON, "el")
	new Struct("governa genaral", 6, PERSON, "al")
	new Struct("youth", 1, PERSON, "ut", [PRON, POSTADJ])
	new Struct("ghetto youth", 3, PERSON, "ut", [PRON, POSTADJ])
	new Struct("speaker", 2, PERSON, "ika")
	new Struct("man", 1, PERSON, "an", [PRON, POSTADJ])
	new Struct("woman", 2, PERSON, "an", [PRON, POSTADJ])
	new Struct("ganja man", 3, PERSON, "an")
	new Struct("rude bway", 2, PERSON, "ai", [POSTADJ])
	new Struct("bad bway", 2, PERSON, "ai")
	new Struct("sound bway", 2, PERSON, "ai")
	new Struct("Jamaican", 3, PERSON, "ca")
	new Struct("Maker", 2, PERSON, "ca")
	new Struct("di Maker", 2, PERSON, "ca")
	new Struct("Emperror Selassie", 6, PERSON, "si")
	new Struct("Selassie I", 4, PERSON, "ai")
	new Struct("mankind", 2, PERSON, "ai")
	new Struct("alla mankind", 4, PERSON, "ai")
	new Struct("Ragamuffin", 4, PERSON, "in")
	new Struct("gyal", 1, PERSON, "al")

	// like
	new Struct("Bob Marley", 3, LIKETHIS, "li")
	new Struct("long time ting", 3, LIKETHIS, "in")
	new Struct("a bat outta hell", 5, LIKETHIS, "el")
	new Struct("we nuh care at all", 5, LIKETHIS, "al")
	new Struct("Jah make we see", 4, LIKETHIS, "si")
	new Struct("dem nuh give no damn", 4, LIKETHIS, "an")
=======


	// [FILLER]
	new Struct("mi seh", 2, FILLER, "")
	new Struct("a mi seh", 2, FILLER, "")
	new Struct("boom", 1, FILLER, "")
	new Struct("oom", 1, FILLER, "")
	new Struct("Lord have mercy", 2, FILLER, "")
	new Struct("sekkle", 2, FILLER, "")
	new Struct("man come", 2, FILLER, "")
	new Struct("watch out", 2, FILLER, "")
	new Struct("cause", 1, FILLER, "")
	new Struct("cah", 1, FILLER, "")
	new Struct("nuh mean", 2, FILLER, "")
	new Struct("mi tell you", 2, FILLER, "")
	new Struct("hear me", 2, FILLER, "")
	new Struct("man", 1, FILLER, "")
	new Struct("live it up", 3, FILLER, "")

	// [PRON]
	new Struct("we", 1, PRON, "i")
	new Struct("we all", 1, PRON, "al")
	new Struct("mi", 1, PRON, "i")
	new Struct("mi", 1, PRON, "i")
	new Struct("mi", 1, PRON, "i")
	new Struct("I", 1, PRON, "ai")
	new Struct("I and I", 1, PRON, "ai")
	new Struct("rastafari", 4, PRON, "ai")
	new Struct("unu", 1, PRON, "u")
	new Struct("dem", 1, PRON, "em")
	new Struct("dem", 1, PRON, "em")
	new Struct("dem", 1, PRON, "em")
	new Struct("she", 1, PRON, "i")
	new Struct("him", 1, PRON, "im")
	new Struct("it", 1, PRON, "it")
	new Struct("man", 1, PRON, "it")
	new Struct("I man", 1, PRON, "it")

	// [PREADJ]
	new Struct("ya", 1, PREADJ, "")
	new Struct("mi", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("di", 1, PREADJ, "")
	new Struct("de", 1, PREADJ, "")
	new Struct("da", 1, PREADJ, "")
	new Struct("another", 2, PREADJ, "")
	new Struct("every", 3, PREADJ, "")
	new Struct("a", 1, PREADJ, "")
	new Struct("some", 1, PREADJ, "")
	new Struct("one", 1, PREADJ, "")

	// [POSTADJ]
	new Struct("dead", 1, POSTADJ, "ed")
	new Struct("good", 1, POSTADJ, "ud")
	new Struct("hot", 1, POSTADJ, "at")
	new Struct("high", 1, POSTADJ, "ai")
	new Struct("wise", 1, POSTADJ, "ais")
	new Struct("mean", 1, POSTADJ, "in")
	new Struct("green", 1, POSTADJ, "in")
	new Struct("clean", 1, POSTADJ, "in")
	new Struct("unseen", 1, POSTADJ, "in")
	new Struct("mad", 1, POSTADJ, "ad")
	new Struct("strong", 1, POSTADJ, "ad")
	new Struct("alright", 2, POSTADJ, "ait")
	new Struct("original", 4, POSTADJ, "al")
	new Struct("crucial", 2, POSTADJ, "al")
	new Struct("tall", 1, POSTADJ, "al")

	// [PREP]
	new Struct("for", 1, PREP, "")
	new Struct("like", 1, PREP, "")

	// [LOCPREP]
	new Struct("inna", 1, LOCPREP, "")
	new Struct("a", 1, LOCPREP, "")
	new Struct("back inna", 2, LOCPREP, "")
	new Struct("in", 1, LOCPREP, "")
	new Struct("from", 1, LOCPREP, "")
	new Struct("round", 1, LOCPREP, "")
	new Struct("back to", 2, LOCPREP, "")
	new Struct("back a", 2, LOCPREP, "")
	new Struct("outta", 2, LOCPREP, "")
	new Struct("straight outta", 3, LOCPREP, "")

	// [LOCATION]
	new Struct("Jamaica", 3, LOC, "ca")
	new Struct("Jamdong", 2, LOC, "own")
	new Struct("Kingston", 2, LOC, "own")
	new Struct("yard", 1, LOC, "ad")
	new Struct("Orange Hill", 3, LOC, "il")
	new Struct("Saint Anne", 2, LOC, "an")
	new Struct("Holy Land", 3, LOC, "an")
	new Struct("London", 2, LOC, "an")
	new Struct("Amstadam", 3, LOC, "an")
	new Struct("Carrabian", 3, LOC, "an")
	new Struct("England", 2, LOC, "an")
	new Struct("Promised Land", 3, LOC, "an")
	new Struct("di system", 3, LOC, "em")
	new Struct("Great Britain", 2, LOC, "em")
	new Struct("mama Africa", 5, LOC, "ca")
	new Struct("God's acre", 3, LOC, "ca")
	new Struct("Mount Zion", 3, LOC, "an")
	new Struct("Angola", 3, LOC, "la")
	new Struct("town", 3, LOC, "on")
	new Struct("Brooklyn", 2, LOC, "in")


	// [TIME]
	new Struct("last night", 2, TIME, "ait")
	new Struct("today", 2, TIME, "ei")
	new Struct("inna di morning", 4, TIME, "in")
	new Struct("pon de place", 3, TIME, "es")
	new Struct("inna whim", 3, TIME, "im")

	// [VERB]
	new Struct("ring", 1, VERB, "in")
	new Struct("sing", 1, VERB, "in")
	new Struct("fling", 1, VERB, "in")
	new Struct("repeat", 2, VERB, "it")
	new Struct("spit", 1, VERB, "it")
	new Struct("play", 1, VERB, "ei")
	new Struct("say", 1, VERB, "ei")
	new Struct("pray", 1, VERB, "ei")
	new Struct("gray", 1, VERB, "ei")
	new Struct("come", 1, VERB, "om")
	new Struct("overcome", 3, VERB, "om")
	new Struct("bun", 1, VERB, "om")
	new Struct("bless up", 2, VERB, "op")
	new Struct("bun up", 2, VERB, "op")
	new Struct("blaze up", 2, VERB, "op")
	new Struct("stop", 1, VERB, "op")
	new Struct("pressure", 2, VERB, "ja")
	new Struct("think", 1, VERB, "in")
	new Struct("see", 1, VERB, "i")
	new Struct("try", 1, VERB, "ai")
	new Struct("tremble", 2, VERB, "el")
	new Struct("wrestle", 2, VERB, "el")
	new Struct("meddle", 2, VERB, "el")
	new Struct("sekkle", 2, VERB, "el")
	new Struct("revel", 2, VERB, "el")
	new Struct("struggle", 2, VERB, "el")
	new Struct("assemble", 3, VERB, "el")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("a", 1, VERB, "")
	new Struct("jump", 1, VERB, "")
	new Struct("drop", 1, VERB, "")
	new Struct("know", 1, VERB, "own")
	new Struct("digress", 2, VERB, "es")
	new Struct("impress", 2, VERB, "es")
	new Struct("bless", 1, VERB, "es")
	new Struct("rise", 1, VERB, "ais")
	new Struct("empathize", 3, VERB, "ais")
	new Struct("setup", 2, VERB, "eta")
	new Struct("take", 1, VERB, "ek")
	new Struct("shake", 1, VERB, "ek")
	new Struct("beg", 1, VERB, "ek")
	new Struct("make", 3, VERB, "ek")
	new Struct("let go pon", 3, VERB, "an")
	new Struct("awaken", 3, VERB, "ca")
	new Struct("fall", 1, VERB, "al")
	new Struct("ball", 1, VERB, "al")

	// [XPR] [VERBEXPR]
	new Struct("smoke di weed", 3, VERBXPR, "id")
	new Struct("smoke di herb", 3, VERBXPR, "erb")
	new Struct("eyes turn red", 3, VERBXPR, "ed")
	new Struct("see it through", 3, VERBXPR, "u")
	new Struct("take a break", 3, VERBXPR, "ek")
	new Struct("do something wrong", 5, VERBXPR, "on")
	new Struct("will be alright", 5, VERBXPR, "on")
	new Struct("do betta", 3, VERBXPR, "eta")
	new Struct("digress", 2, VERBXPR, "es")
	new Struct("guess", 1, VERBXPR, "es")
	new Struct("stress", 1, VERBXPR, "es")
	new Struct("dress ", 1, VERBXPR, "es")

	// [PREF] [VERBPREF]
	new Struct("smoke", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("blaze up", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("bubble", 2, VERBPREF, "", [], SMOKABLE)
	new Struct("get", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("roll up", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("smuggle", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("bake", 1, VERBPREF, "", [], SMOKABLE)
	new Struct("draw", 1, VERBPREF, "", [], SMOKABLE)

	new Struct("aknowledge", 3, VERBPREF, "ij", [], CONCEPT)
	new Struct("achieve", 2, VERBPREF, "iv", [], CONCEPT)
	new Struct("give out", 2, VERBPREF, "out", [], CONCEPT)
	new Struct("learn about", 1, VERBPREF, "out", [], CONCEPT)
	new Struct("have", 2, VERBPREF, "av", [], CONCEPT)
	new Struct("praise", 1, VERBPREF, "es", [], CONCEPT)
	new Struct("spread", 1, VERBPREF, "ed", [], CONCEPT)
	new Struct("sekkle pon", 1, VERBPREF, "on", [], CONCEPT)
	new Struct("prolong", 1, VERBPREF, "on", [], CONCEPT)
	new Struct("bless", 1, VERBPREF, "es", [], CONCEPT)
	new Struct("express", 2, VERBPREF, "es", [], CONCEPT)
	new Struct("confess", 2, VERBPREF, "es", [], CONCEPT)
	new Struct("address", 2, VERBPREF, "es", [], CONCEPT)

	new Struct("talk to", 2, VERBPREF, "u", [], PERSON)
	new Struct("listen to", 3, VERBPREF, "u", [], PERSON)
	new Struct("be like", 2, VERBPREF, "u", [], PERSON)
	new Struct("turn in", 2, VERBPREF, "in", [], PERSON)
	new Struct("praise", 2, VERBPREF, "es", [], PERSON)
	new Struct("praise", 2, VERBPREF, "es", [], PERSON)
	new Struct("impress", 3, VERBPREF, "es", [], PERSON)
	new Struct("brutalize", 3, VERBPREF, "ize", [], PERSON)

	//new Struct("shoot", 3, VERBPREF, "ut", [], MUSIC)

	// [MODALVERB]
	new Struct("want fi", 1, 		MODALVERB, "", [])
	new Struct("can", 1, 			MODALVERB, "", [])
	new Struct("affi", 2, 			MODALVERB, "", [])
	new Struct("nuh go", 2, 		MODALVERB, "", [])
	new Struct("a go", 2, 			MODALVERB, "", [])
	new Struct("like", 1, 			MODALVERB, "", ["to", "fi"])
	new Struct("let", 1, 			MODALVERB, "", [PRON])
	new Struct("neva", 2, 			MODALVERB, "", [])
	new Struct("neva eva", 3,		MODALVERB, "", [])
	new Struct("done", 1,			MODALVERB, "", [])
	new Struct("see dat", 2,		MODALVERB, "", [PRON, PERSON])
	new Struct("make sure dat", 3,	MODALVERB, "", [PRON, PERSON])
	new Struct("said", 1, 			MODALVERB, "", [PRON, PERSON])
	new Struct("shall", 1, 			MODALVERB, "", [])
	new Struct("will have to", 2, 	MODALVERB, "", [])
	new Struct("make", 1, 			MODALVERB, "", [PRON])

	// [ADV]
	new Struct("away", 1, ADV, "ei")
	new Struct("ahead", 2, ADV, "ed")
	new Struct("to di top", 3, ADV, "op")
	new Struct("again", 2, ADV, "em")
	new Struct("down", 1, ADV, "own")
	new Struct("over", 2, ADV, "va")
	new Struct("hard", 2, ADV, "ad")
	new Struct("wrong", 2, ADV, "on")

	// [SMOKABLE]
	new Struct("weed", 1, SMOKABLE, "id")
	new Struct("ganja", 2, SMOKABLE, "ja")
	new Struct("sensi", 2, SMOKABLE, "si")
	new Struct("herb", 1, SMOKABLE, "erb")
	new Struct("bong", 1, SMOKABLE, "on")
	new Struct("sensimilia", 4, SMOKABLE, "ia")
	new Struct("sess", 1, SMOKABLE, "es")
	new Struct("spliff", 1, SMOKABLE, "if")
	new Struct("bud", 1, SMOKABLE, "od")
	new Struct("grass", 1, SMOKABLE, "as")
	new Struct("green", 1, SMOKABLE, "in")
	new Struct("sweet Mary Jane", 4, SMOKABLE, "ein")
	new Struct("Mary Jane", 3, SMOKABLE, "ein")
	new Struct("marijuana", 4, SMOKABLE, "ana")
	new Struct("cana", 2, SMOKABLE, "ana")
	new Struct("pot", 1, SMOKABLE, "at")
	new Struct("420", 3, SMOKABLE, "ti")
	new Struct("blunt", 1, SMOKABLE, "on")
	new Struct("chronic", 2, SMOKABLE, "ic")
	new Struct("fyah", 2, SMOKABLE, "ia")
	new Struct("cali", 2, SMOKABLE, "li")

	// Achieve, give out, praise, spread, sekkle
	new Struct("highest grade", 3, CONCEPT, "ed")
	new Struct("mayhem", 2, CONCEPT, "em")
	new Struct("big man thing", 1, CONCEPT, "in")
	new Struct("thing", 1, CONCEPT, "in")
	new Struct("sound", 1, CONCEPT, "own")
	new Struct("jah", 1, CONCEPT, "ja")
	new Struct("jahjah", 2, CONCEPT, "ja")
	new Struct("ganja", 2, CONCEPT, "ja")
	new Struct("culture", 2, CONCEPT, "ja")
	new Struct("dispute", 2, CONCEPT, "ut")
	new Struct("stress", 1, CONCEPT, "es")
	new Struct("happiness", 3, CONCEPT, "es")
	new Struct("rightousness", 3, CONCEPT, "es")
	new Struct("distress", 2, CONCEPT, "es")
	new Struct("finest", 2, CONCEPT, "es")
	new Struct("vibration", 4, CONCEPT, "an")
	new Struct("elevation", 4, CONCEPT, "an")
	new Struct("liberation", 4, CONCEPT, "an")
	new Struct("function", 2, CONCEPT, "an")
	new Struct("redemption", 3, CONCEPT, "an")
	new Struct("destruction", 3, CONCEPT, "an")
	new Struct("seduction", 3, CONCEPT, "an")
	new Struct("introduction", 3, CONCEPT, "an")
	new Struct("truth", 1, CONCEPT, "ut")
	new Struct("new heights", 2, CONCEPT, "ait")
	new Struct("light", 1, CONCEPT, "ait")
	new Struct("love", 1, CONCEPT, "av")
	new Struct("meditation", 4, CONCEPT, "an")
	new Struct("inspiration", 4, CONCEPT, "an")


	// [THING]
	new Struct("rasta", 2, THING, "")
	new Struct("pasta", 2, THING, "")
	new Struct("microphone", 3, THING, "own")
	new Struct("chalice", 3, THING, "is")
	new Struct("block", 1, THING, "ak")
	new Struct("head", 1, THING, "ed")
	new Struct("head", 1, THING, "ed")
	new Struct("bed", 1, THING, "ed")
	new Struct("highest grade", 3, THING, "ed")
	new Struct("bredda", 2, THING, "ed")
	new Struct("rhyme", 1, THING, "ai")
	new Struct("crime", 1, THING, "ai")
	new Struct("dime", 1, THING, "ai")
	new Struct("rude bway", 2, THING, "ai")
	new Struct("bad bway", 2, THING, "ai")
	new Struct("mankind", 2, THING, "ai")
	new Struct("selecta", 3, THING, "ca")
	new Struct("dem", 1, THING, "em")
	new Struct("anthem", 2, THING, "em")
	new Struct("whola dem", 3, THING, "em")
	new Struct("system", 2, THING, "em")
	new Struct("sound system", 3, THING, "em")
	new Struct("dis", 1, THING, "is")
	new Struct("it", 1, THING, "it")
	new Struct("weed", 1, THING, "it")
	new Struct("sound", 1, THING, "own")
	new Struct("song", 1, THING, "own")
	new Struct("song", 1, THING, "on")
	new Struct("crown", 1, THING, "own")
	new Struct("town", 1, THING, "own")
	new Struct("Kingston", 2, THING, "own")
	new Struct("babylon", 2, THING, "own")
	new Struct("two stone", 2, THING, "own")
	new Struct("DJ", 2, THING, "ei")
	new Struct("soldier", 2, THING, "ja")
	new Struct("jah", 1, THING, "ja")
	new Struct("jahjah", 2, THING, "ja")
	new Struct("ganja", 2, THING, "ja")
	new Struct("culture", 2, THING, "ja")
	new Struct("cover", 2, THING, "ova")
	new Struct("rebel", 2, THING, "el")
	new Struct("pebble", 2, THING, "el")
	new Struct("medal", 2, THING, "el")
	new Struct("metal", 2, THING, "el")
	new Struct("pedal", 2, THING, "el")
	new Struct("level", 2, THING, "el")
	new Struct("devil", 2, THING, "el")
	new Struct("vegetable", 4, THING, "el")
	new Struct("table", 2, THING, "el")
	new Struct("dat", 1, THING, "at")
	new Struct("youth", 1, THING, "ut")
	new Struct("roots", 1, THING, "ut")
	new Struct("route", 1, THING, "ut")
	new Struct("suit", 1, THING, "ut")
	new Struct("booth", 1, THING, "ut")
	new Struct("reggae roots", 3, THING, "ut")
	new Struct("house", 1, THING, "ous")
	new Struct("mouse", 1, THING, "ous")
	new Struct("speaker", 2, THING, "ika")
	new Struct("man", 1, THING, "an")
	new Struct("woman", 2, THING, "an")
	new Struct("bataclan", 3, THING, "an")
	new Struct("congress", 2, THING, "e")
	new Struct("disgrace", 2, THING, "es")
	new Struct("address", 2, THING, "es")
	new Struct("regrets", 2, THING, "es")
	new Struct("progress", 2, THING, "es")
	new Struct("place", 2, THING, "es")
	new Struct("medication", 4, THING, "an")
	new Struct("patient", 2, THING, "an")
	new Struct("cultivation", 4, THING, "an")
	new Struct("surprise", 2, THING, "ais")
	new Struct("riddim", 2, THING, "im")
	new Struct("m16", 3, THING, "im")
	new Struct("scheme", 1, THING, "im")
	new Struct("scene", 1, THING, "in")
	new Struct("queen", 1, THING, "in")
	new Struct("caffeine", 2, THING, "in")
	new Struct("eighteen", 2, THING, "in")
	new Struct("hygine", 2, THING, "in")
	new Struct("washing machine", 4, THING, "in")
	new Struct("protein", 2, THING, "in")
	new Struct("Wolverine", 3, THING, "in")
	new Struct("figurine", 3, THING, "in")
	new Struct("green", 1, THING, "in")
	new Struct("backfoot", 2, THING, "ut")
	new Struct("chain breaka", 3, THING, "ca")
	new Struct("Maker", 2, THING, "ca")
	new Struct("care taker", 3, THING, "ca")




	// And [PERSON], all are also considered THIGNS
	new Struct("selecta", 3, PERSON, "ta", [PRON, POSTADJ])
	new Struct("bredda", 2, PERSON, "ed", [PRON, POSTADJ])
	new Struct("bredren", 2, PERSON, "em", [PRON])
	new Struct("dem", 1, PERSON, "em")
	new Struct("whola dem", 3, PERSON, "em")
	new Struct("di whola dem", 3, PERSON, "em")
	new Struct("system", 3, PERSON, "em")
	new Struct("gyal dem", 2, PERSON, "em")
	new Struct("it", 1, PERSON, "it")
	new Struct("DJ", 2, PERSON, "ei", [PRON, POSTADJ])
	new Struct("soldier", 2, PERSON, "ja", [PRON, POSTADJ])
	new Struct("jah", 1, PERSON, "ja")
	new Struct("jahjah", 2, PERSON, "ja")
	new Struct("almighty Jah", 3, PERSON, "ja")
	new Struct("rebel", 2, PERSON, "el", [PRON, POSTADJ])
	new Struct("devil", 2, PERSON, "el")
	new Struct("governa genaral", 6, PERSON, "al")
	new Struct("youth", 1, PERSON, "ut", [PRON, POSTADJ])
	new Struct("ghetto youth", 3, PERSON, "ut", [PRON, POSTADJ])
	new Struct("speaker", 2, PERSON, "ika")
	new Struct("man", 1, PERSON, "an", [PRON, POSTADJ])
	new Struct("woman", 2, PERSON, "an", [PRON, POSTADJ])
	new Struct("ganja man", 3, PERSON, "an")
	new Struct("rude bway", 2, PERSON, "ai", [POSTADJ])
	new Struct("bad bway", 2, PERSON, "ai")
	new Struct("sound bway", 2, PERSON, "ai")
	new Struct("Jamaican", 3, PERSON, "ca")
	new Struct("Maker", 2, PERSON, "ca")
	new Struct("di Maker", 2, PERSON, "ca")
	new Struct("Emperror Selassie", 6, PERSON, "si")
	new Struct("Selassie I", 4, PERSON, "ai")
	new Struct("mankind", 2, PERSON, "ai")
	new Struct("alla mankind", 4, PERSON, "ai")
	new Struct("Ragamuffin", 4, PERSON, "in")
	new Struct("gyal", 1, PERSON, "al")

	// like
	new Struct("Bob Marley", 3, LIKETHIS, "li")
	new Struct("long time ting", 3, LIKETHIS, "in")
	new Struct("a bat outta hell", 5, LIKETHIS, "el")
	new Struct("we nuh care at all", 5, LIKETHIS, "al")
	new Struct("Jah make we see", 4, LIKETHIS, "si")
	new Struct("dem nuh give no damn", 4, LIKETHIS, "an")
>>>>>>> 448db754ee0ecb9f90b82e4acca8d9bce4854101
