	var Names = {};

	var buttons = {
		'Characters' 	: [
			'darkSoulsBoss',
			'dwarfFemale',
			'dwarfSurname',
			'dwarfMale',
			'elfFemale',
			'elfMale',
			'gnomeSurname',
			'goblinFemale',
			'goblinSurname',
			'goblinMale',
			'humanMale',
			'humanMale2',
			'humanMale1',
			'humanSurname',
			'humanFemale',
			'nordicMale',
			'orcMale',
			'pandarenSurname',
			'pandarenFemale',
			'pandarenMale',
			'bandit',
			'ogre',
			'ogreTribe',
			'succubus'

		],
		'Locations'		: [
			'city',
			'tavern',
			'village',
			'water',
			'world',
			'zone',
		],
		'Monsters'		: [
			'shark',
			'boar'
		],
		'Misc'			: [
			'quest',
			'upgrade',
			'spellRogue',
			'spellHoly',
			'spellModifier',
			'spellWarlock',
			'spellMage',
			'mace',
			'sword',
			'lowQualityWeapon',
			'metalCommon',
			'metalFormal',
			'plantFantas',
			'plantCommon',
			'plantFormal',
			'goodOrganization',
			'cult',
			'thievesGuild',
			'voidFaction'
		],
		'Modern'	: [
			'trapper',
			'cookie',
			'eSportsTeam',
			'jew',
			'cookie',
			'eSportsTeam',
			'letter',
			'letterOrNumber',
			'redneck',
			'pimp',
			'programmingLanguage',
			'videoGame',
			'reggaeSinger'
		]
	}

	Names.blank			= function(){
		var q = randomOf();
		var w = randomOf();
		return q + w;
	}

	Names.darkSoulsBoss		= function(){
		var how = randomOf(
			'White',
			'Lone',
			'Undead',
			'Great',
			'Crystal',
			'Old',
			'Last',
			'First',
			'Lost',
			'Silver',
			'Rotten',
			'Vengeful',
			'Phantom',
			'Imprisoned'
		);
		var what = randomOf(
			'Knight',
			'Beast',
			'Dragon',
			'Champion',
			'Giant',
			'Lord',
			'Demon',
			'Guardian',
			'Watcher',
			'Sentry',
			'Ghoul',
			'Eater',
			'Drake',
			'Warden',
			'Wraith',
			'Sage',
			'Corvian',
			'Judicator',
			'Priest',
			'Spirit',
			'Shade',
			'Wolf',
		);
		var ofWhat = randomOf(
			'of Ash',
			'of Farron',
			'of Anor Londo',
			'of the Boreal Valley',
			'of Carthus',
			'of the First Flame',
			'of the Deep',
			'of Oolacile',
			'of Lothric Castle',
			'of Drangleic',
			'of Astora',
			'of Catarina',
			'of the Great Hollow',
			'of the Painted World',
			'of Lost Izalith',
			'of the Harvest Valley',
			'of the Undead Crypt',
			'of the Dragon Aerie',
			'of the Grand Cathedral',
			'of Irithyll',
			'of the Ringed City'
		)
		var locationHow = randomOf(
			'Shallow',
			'White',
			'High',
			'Ashen',
			'King\'s',
			'Profaned',
			'Untended',
			'Consumed',
			'Hollow',
			'Deep',
			'Burried',
			'Cursed',
			'Great',
			'Iron',
			'Sunken',
			'Black'
		)
		var location = randomOf(
			'Grave',
			'Cemetery',
			'Wall',
			'Keep',
			'Cathedral',
			'Valley',
			'King',
			'Lord',
			'Bearer',
			'Cinder',
			'Flame',
			'Shrine',
			'Depths',
			'Garden',
			'Circle',
			'Church',
		)
		return how + ' ' + what + ' ' + randomOf(ofWhat, 'of the ' + locationHow + ' ' + location)
	}

	Names.trapper			= function(){
		var q = randomOf(
			"Lil",
			"Brotha",
			"Gucci",
			"Young",

		);
		var w = randomOf("Pump",
			"Gucci",
			"Ooh"

		);
		return q + w;
	}

	Names.dwarfFemale	= function(){
		var q = randomOf(
			"Hel",
			"Thor",
			"Urs",
			"Groor",
			"Donel",
			"Urs",
			"Gruk",
			"Tungr",
			"Tel",
			"Tol",
			"Dom",
			"Tov",
			"Dug",
			"Rath",
			"Alg",
			"Glor",
			"Bath",
			"Far",
			"Bran",
			"Olin",
			"Er",
			"Farin",
			"Tran",
			"Bar");
		var w = randomOf(
			"sia",
			"ia",
			"ka",
			"ara",
			"gerd",
			"ga",
			"gith",
			"ula",
			"hilda",
			"mena",
			"uela",
			"gret",
			"greth",
			"ora");
		return q + w;
	}
	Names.dwarfSurname	= function(){
		var q = randomOf(
			"Rock",
			"Stout",
			"Guzzle",
			"Gale",
			"Stone",
			"Thunder",
			"Bronze",
			"Gold",
			"Steel",
			"Red",
			"Grey",
			"Black",
			"Iron",
			"White",
			"Grizzle");
		var w = randomOf(
			"bear",
			"brew",
			"arm",
			"horn",
			"hand",
			"mine",
			"beard",
			"beard",
			"hammer",
			"gunt",
			"nail",
			"cliff",
			"forge",
			"mane",
			"grip",
			"brow",
			"back");
		return q + w;
	}
	Names.dwarfMale		= function(){
		var q = randomOf(
			"Bari",
			"Brag",
			"Krol",
			"Ruth",
			"Vor",
			"Buz",
			"Jogh",
			"Umin",
			"Bord",
			"Bard",
			"Berd",
			"Noth",
			"Held",
			"Borst",
			"Holt",
			"Thor",
			"Mag",
			"Vel",
			"Nag",
			"Glar",
			"Mura",
			"Bora",
			"Bor",
			"Vora",
			"Mun",
			"Hugn",
			"Ban",
			"Mod",
			"Lorn",
			"Bael",
			"Grim",
			"Al",
			"Bur",
			"Bura",
			"Dur",
			"Mur",
			"Alam",
			"Bel",
			"Buin",
			"Bur",
			"Bura",
			"Buro");
		var w = randomOf(
			"grus",
			"bi",
			"gas",
			"ni",
			"han",
			"ran",
			"san",
			"din",
			"gis",
			"gus",
			"gud",
			"gard",
			"log");
		return q + w;
	}
	Names.elfFemale		= function(){
		var q = randomOf(
			"E",
			"Ae",
			"A",
			"Shae",
			"Shae",
			"Dae",
			"Casa",
			"Tae",
			"Mi",
			"Ala",
			"Ara",
			"Ana",
			"Tia",
			"Gwen",
			"Quel'a",
			"La",
			"Meli",
			"Eli",
			"Asha",
			"Va",
			"Shala",
			"Sala",
			"Sa",
			"Sha",
			"Shia",
			"Sia",
			"Lia",
			"Ele");
		var w = randomOf(
			"lin",
			"randa",
			"ryn",
			"drith",
			"dolin",
			"sa",
			"ndis",
			"nya",
			"lera",
			"nera",
			"layna",
			"shaelle",
			"melle",
			"relle",
			"lande",
			"rith",
			"ndra",
			"ria",
			"ra",
			"lala",
			"lora",
			"lara",
			"lira",
			"ndria",
			"drin");
		return q + w;
	}
	Names.elfMale		= function(){
		var q = randomOf(
			"Ar",
			"Quel",
			"Que'",
			"Quar",
			"Qor'",
			"Er",
			"Era'",
			"Eo",
			"Shala",
			"Ell",
			"Eon",
			"Ron",
			"Kel'",
			"Tere",
			"Teli",
			"Tali",
			"Terion'",
			"Ysh'",
			"Kirin'",
			"Aeth",
			"Thal'",
			"Tae'",
			"Thae",
			"Lor",
			"As",
			"Drae",
			"Voren",
			"Vor'",
			"Val",
			"Quel",
			"Qual",
			"Qeth");
		var w = randomOf(
			"vanash",
			"ash",
			"dorei",
			"doras",
			"thalas",
			"nar",
			"nor",
			"shal",
			"agon",
			"gon",
			"ion",
			"arion",
			"narion",
			"lash",
			"vash",
			"nin",
			"nesh",
			"arash");
		return q + w;}
	Names.gnomeSurname	= function(){
		var q = randomOf(
			"Click",
			"Sharp",
			"Swift",
			"Little",
			"Short",
			"Glow",
			"Jink",
			"Nickle",
			"Slip",
			"Tech",
			"Puddle");
		var w = randomOf(
			"spring",
			"whistle",
			"finger",
			"gauge",
			"needle",
			"cog",
			"pipev",
			"wrench",
			"foot",
			"pin",
			"tink",
			"widget",
			"glitch",
			"span",
			"clank",
			"spin");
		return q + w;
	}
	Names.goblinFemale	= function(){
		var q = randomOf(
			"Sazzy",
			"Donna",
			"Bambi",
			"Crystal",
			"Tiffany",
			"Amber",
			"Brandy",
			"Cherry",
			"Diamond",
			"Lexie",
			"Roxie",
			"Trixie",
			"Polly",
			"Suzie",
			"Sheila",
			"Evelyn",
			"Wanda",
			"Kristie",
			"Jasmin",
			"Nikki",
			"Lena",
			"Keisha",
			"Izzy",
			"Shayla",
			"Sharon",
			"Jenna",
			"Stacey",
			"Tamika",
			"Shaniqua",
			"Chanelle");
		return q;
	}
	Names.goblinSurname	= function(){
		var q = randomOf(
			"Steam",
			"Bilge",
			"Noggen",
			"Nog",
			"Babble",
			"Gear",
			"Grapple",
			"Scrabble",
			"Hard",
			"Gizmo",
			"Quick",
			"Gripple",
			"Brim",
			"Cable",
			"Rocket",
			"Copper",
			"Fickle",
			"Fiddle",
			"Buckle",
			"Tackle",
			"Scrap",
			"Rubble");
		var w = randomOf(
			"wheedle",
			"fogger",
			"snaff",
			"slipper",
			"wrench",
			"screw",
			"shredder",
			"skimmer",
			"snap",
			"fingers",
			"wheezle",
			"fuse",
			"blast",
			"bolt",
			"swing",
			"buzzle",
			"camp",
			"nickle",
			"pinch",
			"wire",
			"pipe",
			"dash",
			"spragg",
			"spring",
			"spurt",
			"dowser",
			"sprocket",
			"crew",
			"wrecker",
			"lock",
			"sledge",
			"dredger",
			"steamer",
			"craft",
			"link",
			"scrambler",
			"speck",
			"spank",
			"pimp",
			"bend",
			"snicker",
			"sneech",
			"sneeze",
			"boom",
			"spark",
			"crackle",
			"trap",
			"wheel",
			"ratchet",
			"rack",
			"prong",
			"paddle",
			"gadget",
			"latch",
			"rod",
			"glow",
			"hunk",
			"junk",
			"trace",
			"punk");
		return q + w;
	}
	Names.goblinMale	= function(){
		var q = randomOf(
			"Griz",
			"Raz",
			"Rez",
			"Ker",
			"Kak",
			"Nok",
			"Fiz",
			"Triz",
			"Pen",
			"Tink",
			"Iz",
			"Gig",
			"Fin",
			"Sog",
			"Nez",
			"Rit",
			"Pum",
			"Zit",
			"Kraz",
			"Krez",
			"Kruz",
			"Kriz",
			"Driz",
			"Droz",
			"Draz",
			"Druz",
			"Drez",
			"Ret",
			"Rat",
			"Traz",
			"Truz",
			"Troz",
			"Fez",
			"Faz",
			"Fuz",
			"Foz",
			"Graz",
			"Groz",
			"Grez",
			"Gruz",
			"Tam",
			"Kran",
			"Zat",
			"Zig",
			"Zeg",
			"Zog",
			"Rig");
		var w = randomOf(
			"zle",
			"zar",
			"rek",
			"zik",
			"zel",
			"liz",
			"zil",
			"kle",
			"tle",
			"lowe",
			"gaz");
		return q + w;
	}
	Names.humanMale		= function(){
		var q = randomOf(Names.humanMale1, Names.humanMale2);
		return q;
	}
	Names.humanMale2	= function(){
		var q = randomOf(
			"Loth",
			"Fal",
			"Ren",
			"Reh",
			"Faran",
			"Ara",
			"El",
			"Al",
			"Are",
			"Ar",
			"Tor",
			"Cal",
			"Kael",
			"Ron",
			"In",
			"Quen",
			"Erin",
			"Ed",
			"Fred",
			"Tron",
			"Rol",
			"Rod",
			"Ger",
			"Gar",
			"Aran",
			"Fin",
			"Rene",
			"Bene",
			"Ala",
			"Wil",
			"Stron",
			"Sto",
			"Geth",
			"Bal",
			"Kol",
			"Lod",
			"Lar",
			"Newl",
			"Fron");
		var w = randomOf(
			"ren",
			"red",
			"rik",
			"stad",
			"gar",
			"rald",
			"gorn",
			"wen",
			"alt",
			"rond",
			"rod",
			"vik",
			"ven",
			"lon",
			"ias",
			"bran",
			"brad",
			"gram",
			"gham",
			"lod",
			"bal",
			"io",
			"lin",
			"zad",
			"dorn",
			"wick",
			"lon",
			"nalt");
		return q + w;
	}
	Names.humanMale1	= function(){
		var q = randomOf(
			"Aaron",
			"Alva",
			"Clyde",
			"Derick",
			"Donnie",
			"Ed",
			"Jack",
			"John",
			"Kenny",
			"Nelson",
			"Noah",
			"Rolf",
			"Randel",
			"Austin",
			"Bruce",
			"Charlie",
			"George",
			"Jaime",
			"Tywin",
			"Sean",
			"Steven",
			"Donnie",
			"Father",
			"Simon",
			"Warren" ,
			"Brendan",
			"Richard",
			"William",
			"Jonah",
			"Alex",
			"Jake",
			"Edward",
			"Wheaton",
			"Elvis",
			"Robert",
			"Michael",
			"David",
			"Daniel",
			"Mark",
			"Paul",
			"Charles",
			"Timothy",
			"Frank",
			"Peter",
			"Harrison",
			"Nathan",
			"Ben",
			"Mason420BlazeItILLIMUNATICONFIRMEDPLS",
			"Liam",
			"Muhammad");
		return q;
	}
	Names.humanSurname	= function(){
		var q = randomOf(
			"Robertson ",
			"Flynn ",
			"Fry ",
			"Tyler ",
			"Osborn ",
			"Freeman ",
			"Miller ",
			"Smith ",
			"Williams ",
			"Brown ",
			"Miller ",
			"Jones ",
			"Moore ",
			"Wright ",
			"Kings ",
			"Green ",
			"Campbell ",
			"Carter ",
			"Roberts ",
			"Steward",
			"Wood ",
			"Grey ",
			"Hughes ",
			"Fisher ",
			"Wilson ",
			"Pressler ",
			"Hicks ",
			"Rogers ",
			"Potts ",
			"Black ",
			"Wrynn ",
			"Fitch ",
			"Folsom ",
			"Field ",
			"Gregory ",
			"Wilfort ",
			"Tillsdale ",
			"Locke ",
			"Martin ",
			"Weller ",
			"Herald ",
			"Granger ",
			"Barnaby ",
			"Meyer ",
			"Jackson ",
			"Vaughn ",
			"Pressler ",
			"Tanner ",
			"Rowe ");
		return q;
	}
	Names.humanFemale	= function(){
		var q = randomOf(
			"Adela ",
			"Adelaide ",
			"Mother ",
			"Helga ",
			"Becky ",
			"Sophie ",
			"Juliet ",
			"Margot ",
			"Dareth ",
			"Shelby ",
			"Aldin ",
			"Steven ",
			"Grif ",
			"Hegnar ",
			"Jordan ",
			"Deena ",
			"Kendra ",
			"Carson ",
			"Dorthy ",
			"Helen ",
			"Ella ",
			"Lena ",
			"Sasha ",
			"Triss ",
			"Trisha ",
			"Alissa ",
			"Annie ",
			"Grace ",
			"Lily ",
			"Margery ",
			"Gwen ",
			"Isabelle",
			"Kyrsten ",
			"Catelyn ",
			"Myrra ",
			"Sherrie ",
			"Alyson ",
			"Cindy ",
			"Diana ",
			"Melanie ",
			"Sara ",
			"Lydia ",
			"Madelyn ",
			"Sara ",
			"Deidre ",
			"Liza ",
			"Wilma ",
			"Aisha ",
			"Heather ",
			"Abby ");
		return q;
	}
	Names.nordicMale	= function(){
		var q = randomOf("Hast",
				"Os",
				"Edd",
				"Fred",
				"Or",
				"Arn",
				"Folk",
				"Her",
				"Djon",
				"Tjorn",
				"Hilm",
				"Snor",
				"Styr",
				"Fin",
				"Theo",
				"Thad",
				"Atil",
				"Tus",
				"Fjor",
				"Thor",
				"Bjorn",
				"Tyr",
				"Brad",
				"Ygg",
				"Rod");
		var w = randomOf("in",
				"rin",
				"lfr",
				"lfer",
				"lag",
				"olf",
				"thr",
				"rik",
				"athr",
				"vard",
				"vt",
				"aldr",
				"ldr",
				"iikr",
				"mir",
				"lak",
				"nir",
				"skr",
				"skar");
		return q + w;
	}
	Names.orcMale		= function(){
		var q = randomOf(
			"Mok" ,
			"Lok'",
			"Quil'",
			"Rak'",
			"Rok",
			"Tor",
			"Ur",
			"Orr",
			"Darr'",
			"Gar",
			"Gron",
			"Gnar",
			"Harr",
			"Hrak",
			"Krol",
			"Kron",
			"Kol",
			"Krall'",
			"Karth'",
			"Zug'",
			"Zogg'",
			"Zor'",
			"Xokk'",
			"Rag'",
			"Vrok'",
			"Braak'",
			"Naz'",
			"Nok'",
			"Mor'",
			"O",
			"Grom");
		var w = randomOf(
			"garosh",
			"salok",
			"tar",
			"zug",
			"garon",
			"moga",
			"ogar",
			"zur",
			"shar",
			"gash",
			"gon",
			"kron",
			"zul",
			"rok",
			"gra",
			"grom");
		return q + w;}
	Names.pandarenSurname		= function(){
		var q = randomOf("Cloud",
				"Fire",
				"Storm",
				"Water",
				"Rain",
				"Spirit",
				"Honey",
				"Serpent",
				"Sage",
				"Great",
				"Elder",
				"Young",
				"Honey",
				"Serpent",
				"Sage",
				"Great",
				"Elder",
				"Sky",
				"Silent",
				"Wild",
				"Spring",
				"Summer",
				"Lotus",
				"Dragon",
				"Water",
				"Gentle");
		var w = randomOf("fist",
				"hand",
				"brow",
				"brush",
				"paw",
				"jug",
				"heart",
				"whisper",
				"wind",
				"keg",
				"song",
				"brew",
				"talon",
				"heart",
				"soul",
				"breeze",
				"bloom",
				"petal",
				"stout",
				"singer");
		return q + w;
	}
	Names.pandarenFemale		= function(){
		var q = randomOf("An",
				"Ay",
				"Chin",
				"Jian",
				"Jin",
				"Jing",
				"Ju",
				"Jo",
				"Li",
				"Lai",
				"Lin",
				"Qing",
				"Shu",
				"Shun",
				"Wen",
				"Wo",
				"Way",
				"Yin",
				"Daw",
				"Ay",
				"Ji",
				"Sha",
				"Yi");
		var w = randomOf(
				"La",
				"Sa",
				"Na",
				"Li",
				"Wa",
				"Ya",
				"Lin");
		return randomOf(q, q + lowercaseFirstLetter(w), q + "-" + w);
	}
	Names.pandarenMale			= function(){
		var q = randomOf("Bai",
				"Bao",
				"Bo",
				"Chang",
				"Chen",
				"Cheng",
				"Chin",
				"Chun",
				"Dong",
				"Fen",
				"Fu",
				"He",
				"Hai",
				"Huan",
				"Huang",
				"Jian",
				"Jin",
				"Jing",
				"Ju",
				"Jo",
				"Cho",
				"Li",
				"Lai",
				"Lo",
				"Qiang",
				"Qing",
				"Shu",
				"Sho",
				"Shun",
				"Wen",
				"Wo",
				"Wu",
				"Xue",
				"Yo",
				"Zhen",
				"Zheng",
				"Ao",
				"Ro",
				"Po",
				"Do",
				"Fo",
				"Ho",
				"Haw",
				"Hao",
				"Daw",
				"Shao",
				"Sha",
				"Yi",
				"Chi");
		var w = randomOf("Bai",
				"Bao",
				"Bo",
				"Chang",
				"Chen",
				"Cheng",
				"Chin",
				"Chun",
				"Dong",
				"Fen",
				"Fu",
				"He",
				"Hai",
				"Huan",
				"Huang",
				"Jian",
				"Jin",
				"Jing",
				"Ju",
				"Jo",
				"Cho",
				"Li",
				"Lai",
				"Lo",
				"Qiang",
				"Qing",
				"Shu",
				"Sho",
				"Shun",
				"Wen",
				"Wo",
				"Wu",
				"Xue",
				"Yo",
				"Zhen",
				"Zheng",
				"Ao",
				"Ro",
				"Po",
				"Do",
				"Fo",
				"Ho",
				"Haw",
				"Hao",
				"Daw",
				"Shao",
				"Sha",
				"Yi",
				"Chi");
		return randomOf(q, q + lowercaseFirstLetter(w), q + " " + w);}




	Names.bandit		= function(){
		var q = randomOf(
			"Pad",
			"Black",
			"Wild",
			"Pack",
			"Back",
			"Mad",
			"Sly",
			"Crag",
			"Shark",
			"Red",
			"Cheat",
			"Crook",
			"Red");
		var w = randomOf(
			"foot",
			"knife",
			"dagger",
			"cloak",
			"back",
			"scarf",
			"rob",
			"steal",
			"hand",
			"finger",
			"bag",
			"pocket",
			"pick",
			"lock",
			"jack",
			"shark",
			"scar",
			"eye",
			"hat",
			"pot",
			"blade",
			"rat",
			"patch");
		return q + w;
	}
	Names.boar			= function(){
		var q = randomOf("Muzzle",
				"Bristle",
				"Bramble",
				"Dirt",
				"Muffle",
				"Battle",
				"Mottle",
				"Might",
				"Red",
				"Blood",
				"Rage",
				"Charge",
				"Tackle",
				"Dust",
				"Dredge",
				"Flak",
				"Crag");
		var w = randomOf("snout",
				"tusk",
				"fang",
				"flank",
				"hoff",
				"snuff",
				"hog",
				"hogger",
				"horn",
				"husk",
				"spine",
				"back");
		return q + w;
	}
	Names.ogre			= function(){
		var q = randomOf("Glop",
				"Mug",
				"Hog",
				"Hob",
				"Sog",
				"Blub",
				"Cho",
				"Lum",
				"Lub",
				"Plub",
				"Clum",
				"Dub",
				"Rug");
		var w = randomOf("gut",
				"gup",
				"gud",
				"gul",
				"gub",
				"gal",
				"gag",
				"gug",
				"rog",
				"rob",
				"rub",
				"dum",
				"dup",
				"dur",
				"pem",
				"ble");
		return q + w;
	}
	Names.ogreTribe		= function(){
		var q = randomOf("Stone",
				"War",
				"Rock",
				"Shadow",
				"Blood",
				"Boulder");
		var w = randomOf("mason",
				"bone",
				"gut",
				"maw",
				"head",
				"maul",
				"club",
				"foot",
				"hammer",
				"fist");
		return q + w;
	}
	Names.succubus		= function(){
		var q = randomOf(
			"Temptress ",
			"Seductress ",
			"Delilah ",
			"Jezebel ",
			"Enchantress ",
			"Deviless ",
			"Demoness ",
			"Desiress ",
			"Excitress ",
			"Lover ",
			"Hellmaid ");
		var w = randomOf(
			"the Seductive ",
			"the Sensual ",
			"the Arousing ",
			"the Provocative ",
			"the Sexy ",
			"the Lustful ",
			"the Hungering ",
			"the Urging ",
			"the Rousing ",
			"the Passionate ",
			"the Pleasuring ",
			"the Romantic ",
			"the Amorous ",
			"the Loving ",
			"the Horny ",
			"the Charmer ",
			"the Charming ",
			"of the Dreams ",
			"the Wild ");
		var e = randomOf(
			"Aphrodite",
			"Felicity",
			"Keira",
			"Evelyn",
			"Lexi",
			"Lilith",
			"Maya",
			"Phoeni",
			"Serena",
			"Selena",
			"Zelda",
			"Yelena",
			"Xandra",
			"Xia",
			"Scarlett",
			"Ysenia",
			"Leila",
			"Cassandra",
			"Sasha",
			"Quinn",
			"Paige",
			"Athena",
			"Artemis",
			"Laila",
			"Freya",
			"Diana",
			"Iris",
			"Selene",
			"Hera",
			"Fiora",
			"Eilere",
			"Emmaline",
			"Jade",
			"Ivy",
			"Daphne",
			"Natalie",
			"Elle",
			"Nemesis",
			"Chanel",
			"Nemesis",
			"Davilla",
			"Amelia",
			"Cadence",
			"Blair",
			"Adele");
		if(percentChance(35)) return q + e;
		return q + w;
	}
	Names.shark			= function(){
		var q = randomOf("White",
				"Black",
				"Sharp",
				"Bull",
				"Iron",
				"Muckle",
				"Reef",
				"Blood",
				"Razor",
				"Rake",
				"Murk");
		var w = randomOf("head",
				"nose",
				"fin",
				"gill",
				"tooth",
				"fang",
				"eye",
				"jaws",
				"stalker",
				"maw");
		return q + w;
	}


	Names.quest			= function(){
		var q = randomOf("A Peasant's ",
				"A Delicate ",
				"A Dwarven ",
				"A Political ",
				"An Elf's ",
				"An Orc's ",
				"A Man's ",
				"A King's ",
				"A Guard's ",
				"A Knight's ",
				"A Soldier's ",
				"Warlord's ",
				randomOf("My", "An", "") + "Unfortunate ",
				"A Fortunate ",
				"A Monk's ",
				"A Priest's ",
				"A Woman's ",
				"People's ",
				"Poor Man's ",
				"A Farmer's ",
				"An Ogre's ",
				"A Monster's ",
				"Dead Man's ",
				"A Simple ");
		var w = randomOf("Story ",
				"Journey ",
				"Affairs ",
				"Goods ",
				"Rites ",
				"Quest ",
				"Duty ",
				"Orders ",
				"Trouble ",
				"Message ",
				"Bounty ",
				"Contract ",
				"Request ",
				"Task ",
				"Letter ",
				"Hope ",
				"Favor ",
				"Trinket ",
				"Note ",
				"Plans ",
				"Bargain ",
				"Ransom ",
				"Millstone ",
				"Burden ",
				"Promise ",
				"Mission ",
				"Chore ",
				"Lost Coin ",
				"Lost Sword ",
				"Honor ",
				"Lesson ",
				"Thought ",
				"Fear ",
				"Proposal ",
				"Death ",
				"Birth ",
				"Errand ",
				"Job ",
				"Work ",
				"Treasure ",
				"Fortune ",
				"Regards ");
		var e = randomOf("Gnoll Leader",
				"Bandit Leader",
				"Wild Ghoul",
				"Necromancer",
				"Thuglord",
				"Warlord",
				"Lake Monster",
				"Drunken Dwarf",
				"Forest Witch",
				"Rampaging Panther",
				"Werewolf",
				"Demon",
				"Forest Satyr");
		var r = randomOf("",
				"My ")
			+ randomOf("Strange ",
				"Deliberate ",
				"Decisive ",
				"Unfortunate ",
				"Desperate ",
				"Risky ",
				"Delicate ",
				"Tricky ",
				"Dangerous ",
				"Safe ",
				"Unmanly ",
				"Unknown ",
				"Fortunate ",
				"Rough ");
		var a = randomOf("Actions ",
				"Maneuvers ",
				"Moves ",
				"Plans ",
				"Methods ",
				"Strategies ",
				"Tactics ",
				"Proposal ",
				"Scheme ",
				"Scenario ",
				"Approach ",
				"Tricks ",
				"Story ",
				"Setup ",
				"Path ",
				"Landing ",
				"Signs ");
		var s = randomOf("The Harbinger of ",
				randomOf("The ", "") + "Bringer of ",
				"Towards ",
				"The Start of ",
				"Bringing ",
				"Announcing ",
				"Bringing Forth ",
				"The End of ",
				"Putting an End to ");
		var d = randomOf("War",
				"Love",
				"Dawn",
				"Havoc",
				"Death",
				randomOf("This ", "") + randomOf("New ", "") + "Friendship",
				"Hate",
				"Dusk",
				"Justice",
				"Peace",
				"Daylight",
				randomOf("This ", "a ") + "Battle") + randomOf("...", "!", "");
		var f = randomOf("Cleansing ",
				"Purifying ",
				"Purging ",
				"Desecrating ",
				"Clearing ",
				"Culling ",
				"Healing ",
				"Locating ",
				"Consacrating ");
		var z = randomOf("the Corpses ",
				"the Lake ",
				"the River ",
				"the Beach ",
				"the Monastery ",
				"the Undead ",
				"the Meadow ",
				"the Fields ",
				"the Grave ",
				"the Marsh ",
				"the Scourge ",
				"the Plague",
				"the Sickness ");
		var x = randomOf("Maintaining ",
				"Putting an End to ",
				"In the Center of ",
				"Revealing ",
				"Reversing ",
				randomOf("There Will Be ", "Telling ") + "Stories of ",
				"Continuing ",
				"Strengthening ",
				"Weakening ",
				"Hundering ",
				"The Injustice of ");
		var c = randomOf("the ", "My ", "This ", "Our ") + randomOf("Revolution ",
				"Madness ",
				"Battle ",
				"Corruption ",
				"Order ",
				"Havoc ",
				"Effect",
				"Process",
				"Glory ",
				"Attack ",
				"Army ",
				"Onslaught ",
				"Plague");
		var v = randomOf("A Trip to ",
				"A Journey to ",
				"Pushing Towards ",
				"The Siege on ",
				"The Defense of ",
				"A Message to ",
				"Riding to ",
				"A Letter to ",
				"A Delivery to ",
				"Assaulting ",
				"Escaping from ",
				"Reclaiming ",
				"Laying Waste in ");
		var t = randomOf("Eliminating ",
				"Killing ",
				"Mugging ",
				"Assaulting ",
				"Ambushing ",
				"Resolving with ",
				"Robbing ",
				"Keeping Away ",
				"Slaying ",
				"Stealing from ",
				"A Bargain with ",
				"A Pact With ",
				"Rescuing ",
				"For ");
		var g = randomOf("a Goblin ",
				"the Threat ",
				"a Troll ",
				"the Enemy",
				"a Hero ",
				"the King ",
				"the Baron ",
				"the Witch ",
				"the Wizards ",
				"a Demon ",
				"a Ghost ",
				"a Citizen ",
				"an Ally ",
				"a 'Friend' ",
				"an Ogre ",
				"the Rich ",
				"the Poor ",
				"the Townsfolk ",
				"the Bandits ",
				"the Weak");
		var b = randomOf("Taking ",
				"Taking Back ",
				"Getting Back ",
				"Hiding ",
				"Destroying ",
				"Revendicating ",
				"Looting ",
				"How to Craft ",
				"About ",
				"Retrieving ",
				"Scrounging for ",
				"Obtaining ",
				"Stealing ");
		var y = randomOf(randomOf("The ", "My ", "Those ") + "Ingredients",
				randomOf("The ", "My ", "That ") + "Money",
				randomOf("The ", "My ", "That ") + "Ring",
				randomOf("The ", "My ", "That ") + "Medallion",
				randomOf("The ", "My ", "That ") + "Sword",
				randomOf("The ", "My ", "That ") + "Wand",
				randomOf("The ", "My ", "That ") + "Books",
				randomOf("The ", "My ", "That ", "Some ") + "Gold",
				randomOf("The ", "My ", "That ") + "Shield",
				randomOf("The ", "My ", "That ") + "Dagger",
				randomOf("The ", "My ", "That ") + "Rune",
				randomOf("The ", "My ", "That ") + randomOf("Sweet ", "") + "Love",
				randomOf("The ", "My ", "That ") + "the Gems") + randomOf("...", "");
		var h = randomOf("The Art of ",
				"The Difficulty of ",
				"The Pain of ",
				"The Hardship of ",
				"The Misery of ",
				"The Shame of ",
				"The Mirth of ",
				"The Future of ",
				"The Sorrow of ",
				"The Past of ",
				"In The Glory of ",
				"In The Honor of ",
				"The Dury of ",
				"The Joy of ",
				"The Sadness of ",
				randomOf("This Is Why ", "The Reason ", "Why ") + randomOf("We ", "I ") + randomOf("Hate ", "Enjoy "),
				"The Craft of ");
		var n = randomOf("Stealing ",
				"Killing",
				"Hunting ",
				"Ploughing ",
				"the Rich",
				"Farming",
				"Smuggling ",
				"the Poor",
				"Making Love",
				"an Orc",
				"War");
		var u = randomOf("The Fat ",
				"The Poor ",
				"The Ugly ",
				"The Rampaging ",
				"The Mad ",
				"The Insane ",
				"The Wise ",
				"The Drunk ",
				"The Cruel ",
				"The Foolish ",
				"The Stupid ",
				"The Abusive ",
				"The Perverted ",
				"The Weak-willed ",
				"The Stubborn ",
				"The Lazy ");
		var j = randomOf("The Fat ",
				"The Poor ",
				"The Ugly ",
				"The Rampaging ",
				"The Mad ",
				"The Insane ",
				"The Wise ",
				"The Drunk ",
				"The Cruel ",
				"The Foolish ",
				"The Stupid ",
				"The Abusive ",
				"The Perverted ",
				"The Weak-willed ",
				"The Stubborn ",
				"The Lazy ");
		var m = randomOf("Troll ",
				"Goblin ",
				"Gnoll ",
				"Werewolf ",
				"Vampire ",
				"Warlock ",
				"King ",
				"Baron ",
				"Maid ",
				"Lass ",
				"Lad ",
				"Lady ",
				"Lord ",
				"Gypsy",
				"Priest",
				"Ogre",
				"Cyclop",
				"Behemoth",
				"Viking",
				"Peasant ",
				"Soldier",
				"Orc",
				"Peon",
				"Worker",
				"Guard",
				"Elf",
				"Dwarf",
				"Halfling");
		return randomOf(
			q + w,
			"WANTED: " + e + "'s Head",
			r + w,
			r + a,
			s + d,
			f + z,
			x + c,
			v + Names.city(),
			t + g,
			b + y,
			h + n,
			randomOf(u + "and " + j, u + m));
	}
	Names.upgrade		= function(){
		var q = randomOf(
			"Improved ",
			"Augumented ",
			"Steel ",
			"Steel-Forged ",
			"Deep Sea ",
			"Coral ",
			"Black ",
			"Red ",
			"Blood-Forged ",
			"Lava-Forged ",
			"Storm ",
			"Storm-Forged ",
			"Burning ",
			"Envenomed ",
			"Reinforced ",
			"Spiked ",
			"Red Iron ",
			"Iron ",
			"Chitinous ",
			"Undead ",
			"Dread ",
			"Corpse-Forged ",
			"Arcane-Forged ",
			"Mana-Forged ",
			"Enchanted ",
			"Frost ",
			"Stone ",
			"Runic ",
			"Hardened ",
			"Adapted ",
			"Evolved ",
			"Moon ",
			"Sun ",
			"Stoneskin ",
			"Dragonscale ",
			"Fortified ",
			"Studded ",
			"Refined ",
			"Advanced ",
			"Higher ",
			"Developed ",
			"Enhanced ");
		var w = randomOf("Gunpowder",
			"Shields",
			"Swords",
			"Weapons",
			"Plating",
			"Armor",
			"Hammers",
			"Masonry",
			"Walls",
			"Barricades",
			"Rifles",
			"Bows",
			"Spears",
			"Axes",
			"Arms",
			"Leather",
			"Mail Armor",
			"Plates",
			"Defenses",
			"Attack",
			"Claws",
			"Fangs",
			"Carapace",
			"Hides",
			"Skin",
			"Woodwork",
			"Talons",
			"Feathers",
			"Blades",
			"Scales",
			"Tridents",
			"Constructions");
		return q + w;
	}
	Names.spellRogue	= function(){
		var q = randomOf(
			"Stealth",
			"Hidden",
			"Rage",
			"Battle",
			"War",
			"Heroic",
			"Rage",
			"Fury",
			"Berserker",
			"Mortal",
			"Deadly",
			"Reckless",
			"Blood",
			"Raging",
			"Piercing",
			"Cruel",
			"Warrior",
			"Barbarian",
			"Poisoned",
			"Open",
			"Twisting",
			"Venomous",
			"Relentless",
			"Ruthless",
			"Hungering",
			"Bloodthirsty",
			"Entangling",
			"Evasive",
			"Long",
			"Rapid",
			"Quick",
			"Double",
			"Triple",
			"Vengeance",
			"Focused",
			"Concentrated",
			"Channeled",
			"Sweeping",
			"Lashing",
			"Blinding");
		var w = randomOf(
			"Attack",
			"Strike",
			"Stance",
			"Dash",
			"Bash",
			"Flurry",
			"Stab",
			"Backstab",
			"Ambush",
			"Shot",
			"Arrow",
			"Rush",
			"Taunt",
			"Throw",
			"Wounds",
			"Rend",
			"Bleed",
			"Rupture",
			"Shout",
			"Rampage",
			"Revenge",
			"Execution",
			"Arms",
			"Blade",
			"Smash",
			"Cleave",
			"Blow",
			"Devastation",
			"Spree",
			"Dagger",
			"Knife",
			"Slice",
			"Kick",
			"Gouge",
			"Fist",
			"Pummel",
			"Shiv",
			"Mutilation",
			"Vault",
			"Mark",
			"Spike");
		if(percentChance(20)) return Names.spellModifier() + q + " " + w;
		return q + " " + w;
	}
	Names.spellHoly		= function(){
		var q = randomOf(
			"Holy",
			"Consacrated",
			"Platinum",
			"Retribution",
			"Sun",
			"Crusader",
			"Dawn",
			"Reckoning",
			"Holy",
			"Sanctified",
			"Avenging",
			"Ardent",
			"Truth",
			"Justice",
			"Heaven",
			"Light's",
			"God's",
			"Radiant",
			"Avenger's");
		var w = randomOf(
			"Fire",
			"Smite",
			"Strike",
			"Blade",
			"Punishment",
			"Heal",
			"Infusion",
			"",
			"Shock",
			"Arrow",
			"Shot",
			"Flames",
			"Burn",
			"Nova",
			"Ground",
			"Armor",
			"Shield",
			"Barrier",
			"Gate",
			"Purification",
			"Binding",
			"Bond",
			"Renewal",
			"Spirit",
			"Mend",
			"Soul",
			"Blessing",
			"Charm",
			"Favor",
			"Flash",
			"Light",
			"Radiance",
			"Beacon",
			"Wrath",
			"Seal",
			"Exorcism",
			"Slash",
			"Justice",
			"Glare");
		if(percentChance(20)) return Names.spellModifier() + q + " " + w;
		return q + " " + w;
	}
	Names.spellModifier	= function(){
		var q = randomOf(
			"Mass ",
			"Greater ",
			"Chain ",
			"Lesser ");
		return q;
	}
	Names.spellWarlock	= function(){
		var q = randomOf(
			"Death",
			"Fear",
			"Corruption",
			"Chaos",
			"Demon",
			"Unholy",
			"Inferno",
			"Blood",
			"Soul",
			"Agony",
			"Pain",
			"Mind",
			"Havoc",
			"Hell",
			"Shadow",
			"Dark",
			"Shade",
			"Plague",
			"Scourge",
			"Doom",
			"Dread",
			"Terror",
			"Corpse",
			"Sin's",
			"Noxious",
			"Poison");
		var w = randomOf(
			"Drain",
			"Ray",
			"Bolt",
			"Strike",
			"Spike",
			"Attack",
			"Blast",
			"Burst",
			"Lash",
			"Conjuration",
			"Energy",
			"Tap",
			"Burn",
			"Fire",
			"Flame",
			"Grip",
			"Grasp",
			"Gate",
			"Touch",
			"Reap",
			"Aura",
			"Blade",
			"Prison",
			"Arrow",
			"Cloud",
			"Incantation",
			"Bind",
			"Bash",
			"Block");
		if(percentChance(20)) return Names.spellModifier() + q + " " + w;
		return q + " " + w;
	}
	Names.spellMage		= function(){
		var q = randomOf(
			"Frost",
			"Fire",
			"Flame",
			"Lava",
			"Arcane",
			"Nether",
			"Frostfire",
			"Ice",
			"Cold",
			"Lightning",
			"Thunder",
			"Water",
			"Earth",
			"Wind",
			"Storm",
			"Spirit",
			"Magic",
			"Rune");
		var w = randomOf(
			"Bolt",
			"Burst",
			"Lash",
			"Shackles",
			"Missile",
			"Barrage",
			"Blast",
			"Explosion",
			"Bomb",
			"Nova",
			"Strike",
			"Breath",
			"Lance",
			"Storm",
			"Burn",
			"Orb",
			"Ray",
			"Surge",
			"Whip",
			"Shield",
			"Barrier",
			"infusion",
			"Power",
			"Crush",
			"Shock",
			"Shear",
			"Blade",
			"Bash",
			"Clash",
			"Charge",
			"Overcharge",
			"Mastery",
			"Rush",
			"Smash",
			"Coil",
			"Armor",
			"Clap",
			"Wall",
			"Ray",
			"Grip",
			"Grasp",
			"Touch",
			"Ring",
			"Chains",
			"Prison",
			"Arrow",
			"Pulse",
			"Torrent",
			"Wave",
			"Sear");
		if(percentChance(20)) return Names.spellModifier() + q + " " + w;
		return q + " " + w;
	}
	Names.mace			= function(){
		var q = randomOf(
			"Righteous ",
			"Lavaforged ",
			"Ironforged ",
			"Steelforged ",
			"Earthforged ",
			"Cobaltforged ",
			"Goldforged ",
			"Silverforged ",
			"Crusader's ",
			"Gladiator's ",
			"Warlord's ",
			"Paladin's ");
		var w = randomOf(
			"Skull",
			"Bone",
			"Sledge",
			"Head",
			"Rock",
			"Ice",
			"Stone",
			"Ebon",
			"Rib",
			"Wood",
			"Spine",
			"Steel",
			'Forge'
		);
		var e = randomOf(
			"basher",
			" Smasher",
			"mace",
			"er",
			"maul",
			"hammer",
			"club",
			'grip',
			"mallet",
			"cracker",
			"pounder",
			"slammer",
			" Pulverizer",
			" Sledgehammer",
			" Demolisher",
			" Destroyer",
			"force",
			" Warhammer",
			"dredger",
			"grinder",
			"might",
			" Brutalizer",
			"phage",
			" Shatterer",
			'shatter',
			"flail");
		return q + " " + w + e;
	}
	Names.lowQualityWeapon = function() {
		let q = randomOf(
			'Age-Worn',
			'Flimsy',
			'Rough',
			'Rusted',
			'Rusty',
			'Muck-Encrusted',
			'Dirty',
			'Old',
			'Commoner\'s',
			'Shattered',
			'Small',
			'Whetted',
			'Stone',
			'Crude',
			'Dull',
			'Cracked',
			'Chipped',
			'Bent',
			'Blunted',
			'Loaded',
			'Corroded',
			'Toy',
			'Wooden',
			'Aged',
			'Jagged',
			'Stiff',
			'Jammed',
			'Eroded',
			'Broken',
			'Chiseled',
			'Whittled',
			'Notched',
			'Deteriorating',
			'Improvised',
			'Weathered',
			'Mossy',
			'Fractured',
			'Battered',
			'Withered'

		)
		let weapon = randomOf(
			'Mallet',
			'Blade',
			'Sword',
			'Shortsword',
			'Dagger',
			'Dirk',
			'Knife',
			'Pike',
			'Hilt',
			'Staff',
			'Club',
			'Axe',
			'Mace',
			'Hatchet',
			'Bow'
		)
		return q + ' ' + weapon
	}
	Names.sword			= function(){
		var q = randomOf(
			"Frost",
			"Dark",
			"Blood",
			"Shadow",
			"Rune",
			"Cold",
			"Hate",
			"Ghost",
			"Silver",
			"Gold",
			"Bronze",
			"Thunder",
			"Echo",
			"Oath",
			"Steel",
			"Night",
			"Day",
			"Sun",
			"Life",
			"Moon",
			"Bane",
			"Death",
			"Mage",
			"Pain",
			'Cinder',
			'Dream',
			'Dawn',
			'Venge',
			'Vile',
			'Cruel',
			'Wrath'
		);
		var w = randomOf(
			"mourne",
			"blade",
			"keeper",
			"ward",
			"sword",
			"bringer",
			"eater",
			"slayer",
			"slicer",
			"guard",
			"er",
			"more",
			"saber",
			"bane",
			"fury",
			"reaper",
			"",
			"edge",
			'fury',
			'brand',
			'saber',
			'rive',
			'rend',
			'sever',
			'sunder',
			'maw',
			'scythe',
			'hilt',
			'weaver'
		);
		return q + w;
	}
	Names.dagger = function() {
		let q = randomOf(
			'Blink',
			'Quick',
			'Mage',
			'Shadow',

		)
		let w = randomOf(
			'blade',
			'slit',
			'rend',
			'shank',
			'kris',
			'thorn',
			'fang',
			'rip',
			'slice',
			'shiver'
		)
	}
	Names.axe = function() {
		let q = randomOf(
			'Rage',
			'Blood',
			'Fury'
		)
		let w = randomOf(
			'blade',
			'whirl',
			'fury',
			'reaver',
			'ripper',
			'cleave'
		)
	}
	Names.crab = function() {
		let q = randomOf(
			'Tide',
			'Red',
			'White',
			'Reef',
			'Shore',
			'Ridge',
			'Sea',
			'Shell',
		)
		let w = randomOf(
			'crawler',
			'clasp',
			'clack',
			'clamp',
			'claw',
			'lob',
			'clamb',
			'pincher',
			'clinch',
			'glip',
			'snap',
			'crack',
			'clutch',
			'nip',
			'crab',
			'dredge',
			'click',
			'grab',
			'knuck'


		)
	}

	Names.cookie		= function(){
		var q = randomOf("Choco",
				"Krispy",
				"Milky",
				"Choca",
				"Butter",
				"Honey",
				"Slim ",
				"Crispy",
				"Cocoa",
				"Coffee",
				"Sugar",
				"Creamy",
				"Vita",
				"Sprinkle");
		var w = randomOf("nut",
				"ways",
				"fig",
				"quake",
				"nilla",
				"puffs",
				"rit",
				"kat",
				"pop",
				"freeze",
				"ffin",
				"bar",
				"pick",
				"puff",
				"kinds",
				"scuit",
				"fudge",
				"finger",
				"snap",
				"snack",
				"brownies",
				"truffle",
				"chips");
		return q + w;
	}
	Names.eSportsTeam		= function(){
		var q = randomOf("Xplosion",
				"Vampire",
				"Jester",
				"Zone",
				"Thunder",
				"Tempest",
				"Wave",
				"Burst",
				"Out",
				"Backfire",
				"Igni",
				"Implosion",
				"Implicit",
				"Invictus",
				"Explicit",
				"Vision",
				"Brainstorm",
				"Storm",
				"Diversion",
				"Devise",
				"Fantasy",
				"Feature",
				"Figure",
				"Form",
				"Nihilation",
				"Cataclysm",
				"Titan",
				"Goliath",
				"Colossus",
				"Monster",
				"Spectre",
				"Legacy",
				"White",
				"Black",
				"Reptile");
		var w = randomOf("Fluffy",
				"Magical",
				"Sexy",
				"Fat",
				"Hat",
				"Slim",
				"Milky",
				"Creamy",
				"Chocolate",
				"Brittish",
				"Canadian",
				"Cash",
				"Neon",
				"Good",
				"Alcoholic",
				"Holy",
				"Creepy",
				"Muslim");
		var e = randomOf("Pidgeons",
				"Raccoons",
				"Penguins",
				"Tigers",
				"Bears",
				"Koalas",
				"Gypsies",
				"Bunnies",
				"Unicorns",
				"Horses",
				"Ducks",
				"Geese",
				"Cranes",
				"Pandas",
				"Crows",
				"Pimps",
				"Cows",
				"Oreos");
		var r = randomOf("of Doom",
				"of Death",
				"on Crack",
				"of Hell",
				"of Love",
				"of Happiness",
				"of Joy",
				"of God",
				"on Drugs");
		var a = randomOf("Fire",
				"Flame",
				"Frost",
				"Green",
				"Ice",
				"Water",
				"Flex");
		var s = randomOf("force",
				"fox",
				"form",
				"dash",
				"dogs");
		return randomOf(
			q + randomOf(" eSports", " Gaming"),
			"Team " + q,
			w + " " + e,
			w + " " + e + " " + r,
			e + " " + r,
			a + s + randomOf(" eSports", " Gaming"),
			"Team " + a + s,
			Names.letterOrNumber() + Names.letterOrNumber(),
			Names.letterOrNumber() + Names.letterOrNumber() + Names.letterOrNumber());
	}
	Names.jew			= function(){
		var q = randomOf(
			"Bank",
			"Money",
			"Gold",
			"Rich",
			"Cash",
			"Wealth",
			"Coin");
		var w = randomOf(
			"sack ",
			"master ",
			"hands ",
			"counter ",
			"beard ",
			"finger",
			"hat ",
			"maker ",
			"jew ",
			"man ",
			"face ",
			"scar ",
			"bag ",
			"pistol ",
			"trigger ");
		var e = randomOf(
			"the 'Gasman' ",
			"the 'Showerman' ",
			"the 'Jewster' ",
			"the 'Holoviver' ",
			"the 'Circumciser' ",
			"the 'Exorcist' ");
		var r = randomOf(
			"Nathan",
			"Mort",
			"Adam",
			"David",
			"Ephraim",
			"Elyakim",
			"Elliot",
			"Noah",
			"Sean",
			"Yakov",
			"Sheldon",
			"Morris",
			"Yorick",
			"Isaac",
			"Jacob",
			"Jack",
			"Samuel",
			"Sam",
			"Moses",
			"Sidney",
			"Caleb",
			"Jared",
			"Jaron",
			"Joel",
			"Jonah",
			"Jude",
			"Omar",
			"Zachary",
			"Joshua");
		if (randomInt(1, 5) == 1) return r + ' ' + e
		return r + ' ' + q + ' ' + w
	}
	Names.letter		= function(){
		var q = randomOf(
			"Q",
			"W",
			"E",
			"R",
			"T",
			"Y",
			"U",
			"I",
			"O",
			"P",
			"A",
			"S",
			"D",
			"F",
			"G",
			"H",
			"J",
			"K",
			"L",
			"Z",
			"X",
			"C",
			"V",
			"B",
			"N",
			"M");
		return q;//.toLowerCase();
	}
	Names.letterOrNumber	= function(){
		var q = randomOf("Q",
				"W",
				"E",
				"R",
				"T",
				"Y",
				"A",
				"I",
				"S",
				"D",
				"F",
				"G",
				"H",
				"J",
				"K",
				"L",
				"Z",
				"X",
				"C",
				"V",
				"B",
				"N",
				"M",
				"1",
				"2",
				"3",
				"4",
				"5",
				"6",
				"7",
				"8",
				"9");
		return q;
	}
	Names.redneck		= function(){
		var q = randomOf(
			"Stinky ",
			"Filthy ",
			"Long ",
			"Red ",
			"Yellow ",
			"Two-",
			"Dirty ",
			"Sweaty ",
			"One ",
			"No ",
			"Oily ",
			"Stained ");
		var w = randomOf(
			"Toe ",
			"Foot ",
			"Sock ",
			"Cap ",
			"Spit ",
			"Hand ",
			"Pants ",
			"Shoe ",
			"Boot ",
			"Gun ",
			"Neck ",
			"Nail ",
			"Old ",
			"Young ",
			"Eye ");
		var e = randomOf(
			"Billy ",
			"Bob ",
			"Jimmy ",
			"Bubba ",
			"Timmy ",
			"Johnny ",
			"Dennis ",
			"Dave ",
			"Frank ",
			"Austin ",
			"Buck ",
			"Chester ",
			"Earl ",
			"Joe ",
			"Joey ",
			"Rick ",
			"Ricky ",
			"Bootch ",
			"Will ",
			"Willy ",
			"Jebediah ",
			"Jeremiah ",
			"Gus ");
		if(percentChance(25)){
			return q + e;}
		else return q + w + e;
	}
	Names.pimp			= function(){
		var q = randomOf(
			"Big ",
			"Fresh ",
			"Fat ",
			"Slim ",
			"Cash ",
			"Lil ",
			"Short ",
			"Tall ",
			"Rich ",
			"Sweet ",
			"Low ",
			"Deep ",
			"Large ",
			"Smooth ",
			"Soft ",
			"Sleek ",
			"Easy ",
			"Late ",
			"Full ",
			"Magic ",
			"Holy ",
			"Slight ",
			"Chunky ",
			"Greasy ",
			"Fishy ",
			"Cash ",
			"Green ",
			"Crispy ",
			"Early ");
		var w = randomOf(
			"'Magic' ",
			"Gypsyboy",
			"Doctor ",
			"Master ",
			"Daddy ",
			"Papa ",
			"Uncle ",
			"King ",
			"Doc ",
			"Pops ",
			"Boy ",
			"Prince ",
			"Brother ",
			"Father ",
			"Grandpa ",
			"Baby ",
			"Santa ");
		var e = randomOf(
			"Jerry",
			"E",
			"T",
			"P",
			"D",
			"G",
			"J",
			"C",
			"B",
			"Ben",
			"Francis",
			"Timmy",
			"Jimmy",
			"John",
			"Smith",
			"Tommy",
			"Danny",
			"Jiggy");
		if(percentChance(20)){
			return w + e;}
		else return q + w + e;
	}
	Names.programmingLanguage	= function(){
		var q = randomOf(
			"#",
			"-Core",
			"+",
			"++",
			"+++",
			" Plus",
			" Plus Plus",
			"Double",
			"Triple",
			"+",
			"#",
			"2",
			"3",
			"4",
			"5",
			".com",
			".net",
			"--",
			"/",
			" Script",
			"-code",
			" .NET",
			"360'",
			"180",
			"90",
			"1k",
			" Turbo",
			"Sharp",
			"X",
			" 2k",
			"log",
			" Portable",
			" Framework",
			"lang",
			"~~");
		var w = randomOf(
			"Ape",
			"K2",
			"Denali",
			"Elbrus",
			"Blanc",
			"Black",
			"White",
			"Redd",
			"Red",
			"Green",
			"Yellow",
			"Teal",
			"Sea",
			"Blue",
			"Bloo",
			"Orange",
			"Apple",
			"Brown",
			"Ban",
			"Spray",
			"box",
			"digital",
			"bott",
			"rain",
			"Cherry",
			"Pear",
			"Plum",
			"Dogg",
			"Katt",
			"Melon",
			"lemon",
			"mango",
			"CoCoNut",
			"POMELO",
			"WMelon",
			"banana",
			"ROOT",
			"pepper",
			"Sprout",
			"Corn",
			"TOMATO",
			"shrppm",
			"dc",
			"bbc",
			"Ocean",
			"Expanse",
			"Lake",
			"pond",
			"SURF",
			"Sk8",
			"wave",
			"Absciss",
			"360-",
			"average",
			"ave",
			"Eve",
			"Algo",
			"Bino",
			"count",
			"domain",
			"Locus",
			"Lux",
			"Lexicon",
			"math",
			"Matrix",
			"NumeratE",
			"sum",
			"Orem",
			"prog",
			"Abstract",
			"Canvas",
			"Acrobat",
			"Dino",
			"Access",
			"reg",
			"booK",
			"MAP",
			"Prog",
			"basic",
			"Logic",
			"hACK",
			"Compi",
			"ware",
			"API",
			"ject",
			"ob J",
			"lit",
			"West",
			"South",
			"nord",
			"starr",
			"Eest",
			"Montana",
			"Dakota",
			"Ohio",
			"Hawaii",
			"Iowa",
			"Tx",
			"Texas",
			"York",
			"Nile",
			"amazon",
			"River",
			"Yangtze",
			"Kongo",
			"Niger",
			"Lena");
		var e = Names.letter();
		if(percentChance(80)) e += Names.letter();
		if(percentChance(70)) e += Names.letter();
		if(q == "~~"){
			q = "." + Names.letter() + Names.letter();
			if(percentChance(50)) q += Names.letter();
			if(percentChance(50)) q = q.toLowerCase();}
		return randomOf(w + q, e + q, e + w);
	}
	Names.videoGame		= function(){
		var q = randomOf(
			"Over",
			"Blast",
			"Flame",
			"Fire",
			"War",
			"Half",
			"Metal",
			"Dead",
			"Dread",
			"Waste",
			"Border",
			"Hype",
			"Bleak",
			"Quarter",
			"Star",
			"Car",
			"Scrap");
		var w = randomOf(
			"blast",
			"land",
			"crash",
			"cram",
			"stance",
			"lands",
			"zone",
			"log",
			"spark",
			"storm",
			"hog",
			"dog",
			"shock",
			"stalk",
			"flame",
			"watch",
			"craft");
		return q + w;
	}


	Names.metalCommon	= function(){
		var q = randomOf(
			"Frost",
			"Cold",
			"Dragon",
			"Flame",
			"Dark",
			"White",
			"Nether",
			"True",
			"True",
			"Forge",
			"Earth",
			"Sky",
			"Red",
			"Blood",
			"Blue",
			"Black",
			"Green",
			"Cloud",
			"New",
			"Old",
			"Feeble",
			"Free",
			"Rune",
			"Glyph",
			"Strong",
			"Pink",
			"Dwarf",
			"Ghost",
			"Fel",
			"Water",
			"Snow",
			"Lava",
			"Life",
			"Death",
			"Great");
		var w = randomOf(
			"stone",
			"iron",
			"gold",
			"silver",
			"cobalt",
			"bronze",
			"copper",
			"steel",
			"gem",
			"ore",
			"glass");
		return q + w;
	}
	Names.metalFormal	= function(){
		var q = randomOf(
			"Dragon",
			"Drak",
			"Drag",
			"Drak",
			"Meteor",
			"Ir",
			"Ar",
			"Ur",
			"Fyr",
			"Or",
			"Kir",
			"Kar",
			"Er",
			"Quar",
			"Grel",
			"Met",
			"Rex",
			"Zex",
			"Krolm",
			"Krol",
			"Dron",
			"Eter",
			"Etern",
			"Scorp",
			"Deter",
			"Den",
			"Amar",
			"Ren",
			"Merk",
			"Mithril",
			"Ban",
			"Arth",
			"Rev",
			"Nem",
			"Pleth",
			"Peiad",
			"Aiad",
			"Gaiad",
			"Veled",
			"Valen",
			"Emb",
			"Rub",
			"Ocen",
			"Sear",
			"Coll",
			"Flam",
			"Ign",
			"Ax",
			"Kern",
			"Chre",
			"Act",
			"Actin",
			"Acter",
			"Eser",
			"Ag",
			"Am",
			"An",
			"Aer",
			"Agad",
			"Alm",
			"Elm",
			"Olm",
			"Azm",
			"Azam",
			"Ezim",
			"Azer",
			"Amb",
			"Car",
			"Corr",
			"Cass",
			"Cat",
			"Chrom",
			"Chron",
			"Rech",
			"Ocher",
			"Orch",
			"Garn",
			"Prais",
			"Thor",
			"Pren",
			"Cit",
			"Oran",
			"Red",
			"Lem",
			"Gnor",
			"Karth",
			"Karthal",
			"Azen",
			"Neven",
			"Nev",
			"Tror",
			"Cind",
			"Enst",
			"Tigr",
			"Lion",
			"Warm",
			"Zirc",
			"Starr");
		var w = randomOf(
			"ium",
			"ite",
			"odium",
			"iun",
			"ine",
			"idium",
			"anium",
			"onium",
			"iode",
			"ide");
		return q + w;
	}
	Names.plantFantasy	= function(){
		var q = randomOf(
			"Peasant's ",
			"King's ",
			"Monk's ",
			"Witch's ",
			"Dragon's ",
			"Ghoul's ",
			"Elvish ",
			"Corrupted ",
			"Fisher's ",
			"Eagle's ",
			"Cat's ",
			"Dog's ",
			"Lady's ",
			"Baron's ",
			"Gypsy ",
			"Lord's ",
			"Wither's ",
			"Knight's ",
			"Demon's ",
			"Angel's ",
			"Cursed ",
			"Holy ",
			"Dwarven ");
		var w = randomOf(
			"leaf",
			"bloom",
			"root",
			"thorn",
			"weed",
			"kelp",
			"moss",
			"branch",
			"grass",
			"foil",
			" Lotus",
			"shroom",
			"cap",
			"thistle",
			"herb",
			"berry",
			"sprout",
			" Tulip",
			" Rose",
			"bell",
			"brush",
			"blossom",
			"clover",
			"fin",
			" Orchid",
			"sage",
			"flower",
			"thyme",
			"blossom",
			"nettle",
			" Lilly",
			"seed",
			"nip",
			"vine",
			"fern",
			"mary");
		w = capitalizeFirstLetter(w);
		return q + w;
	}
	Names.plantCommon	= function(){
		var q = randomOf(
			"Peace",
			"War",
			"Silver",
			"Gold",
			"Bronze",
			"Steel",
			"Iron",
			"Red",
			"Blue",
			"Black",
			"White",
			"Earth",
			"Sky",
			"Cloud",
			"Death",
			"Life",
			"Grave",
			"Swift",
			"Slow",
			"Brair",
			"Lion",
			"Wolfs",
			"Blood",
			"Whisker",
			"Fire",
			"Frost",
			"Cold",
			"Warm",
			"Hot",
			"Day",
			"Night",
			"Dusk",
			"Dawn",
			"Purple",
			"Sun",
			"Moon",
			"Sorrow",
			"Mirth",
			"Cinder",
			"Ash",
			"Ember",
			"Ruby",
			"Glory",
			"Rage",
			"Flame",
			"Nether",
			"Tiger",
			"Rain",
			"Drought",
			"Star",
			"Echo",
			"Thunder",
			"Dark",
			"Light",
			"Water",
			"Sea",
			"Swamp",
			"Marsh",
			"Field",
			"Summer",
			"Fall",
			"Riser",
			"Spring",
			"Cave",
			"Hate",
			"Tumble",
			"Wine",
			"Grape",
			"Merry",
			"Knettle",
			"Wit",
			"Smite",
			"Drake",
			"Dragon",
			"Were",
			"Barren",
			"Dry",
			"Bleak",
			"Honey");
		var w = randomOf(
			"leaf",
			"bloom",
			"root",
			"thorn",
			"weed",
			"kelp",
			"moss",
			"branch",
			"grass",
			"foil",
			" Lotus",
			"shroom",
			"cap",
			"thistle",
			"herb",
			"berry",
			"sprout",
			" Tulip",
			" Rose",
			"bell",
			"brush",
			"blossom",
			"clover",
			"fin",
			" Orchid",
			"sage",
			"flower",
			"thyme",
			"blossom",
			"nettle",
			" Lilly",
			"seed",
			"nip",
			"vine",
			"fern",
			"mary");
		return q + w;
	}
	Names.plantFormal	= function(){
		var q = randomOf(
			"Saram",
			"Lavan",
			"Celan",
			"Cindin",
			"Cin",
			"Lav",
			"Sar",
			"Quar",
			"Wir",
			"Wex",
			"Epsen",
			"Epsin",
			"Alco",
			"Rit",
			"Riven",
			"Rar",
			"Ral",
			"Riva",
			"Telur",
			"Tar",
			"Thoran",
			"Taran",
			"Reval",
			"Yog",
			"Ur",
			"Inrin",
			"Yngrun",
			"Ox",
			"Oxen",
			"Potan",
			"Potal",
			"Sartem",
			"Dorak",
			"Der",
			"Apin",
			"Hal",
			"Heder",
			"Aether",
			"Gan",
			"Gramem",
			"Jivim",
			"Kiril",
			"Lotar",
			"Zax",
			"Zaxer",
			"Zaxem",
			"Xisen",
			"Xim",
			"Con",
			"Connin",
			"Ambicon",
			"Dem",
			"Demim",
			"Viscan",
			"Velen",
			"Berrin",
			"Ber",
			"Naxin",
			"Verin",
			"Nether",
			"Mand",
			"Mander",
			"Aman",
			"Amar",
			"Aster",
			"Mander",
			"Aman",
			"Amar",
			"Aster",
			"Emer",
			"Calen",
			"Amal",
			"Iren");
		var w = randomOf(
			"ine",
			"dine",
			"aria",
			"naria",
			"erin",
			"um",
			"der",
			"idion",
			"edum",
			"am",
			"sam",
			"us",
			"cohest",
			"hest",
			"cohol",
			"mine",
			"atus",
			"dis",
			"os",
			"rylis",
			"gonia",
			"gamot",
			"lias",
			"phinum",
			"iolus",
			"andum",
			"dula");
		return q + w;
	}



	Names.city			= function(){
		var q = randomOf(
			"Dragon",
			"Blood",
			"Red",
			"Ever",
			"West",
			"East",
			"South",
			"North",
			"Wind",
			"Harth",
			"Storm",
			"Sea",
			"Lake",
			"River",
			"Hroth",
			"Long",
			"Short",
			"Way",
			"Great",
			"Winter",
			"Summer",
			"Spring",
			"Gold",
			"Black",
			"Dark",
			"Light",
			"Cold",
			"Warm",
			"Wolf",
			"Pike",
			"Strong",
			"Bear",
			"Iron",
			"Snow",
			"Rain",
			"Pendle",
			"Dawn",
			"Sun",
			"Day",
			"Night",
			"Lords",
			"Kings",
			"Stall",
			"Sovern",
			"Brair",
			"Solst",
			"Farren",
			"High",
			"Darn",
			"High");

		var w = randomOf(
			"shire",
			"glen",
			"ridge",
			"town",
			"garden",
			"den",
			"vale",
			"meadow",
			"hill",
			"brad",
			"mire",
			"mill",
			"keep",
			"hold",
			"watch",
			"post",
			"ford",
			"marsh",
			"field",
			"ville",
			"land",
			"fell",
			"shore",
			"guard",
			"garde",
			"wallow",
			"stead",
			"fall",
			"wall",
			"state",
			"run",
			"ward",
			"water",
			"tower",
			"bay",
			"wood",
			"dale",
			"heim",
			"vael",
			"dor",
			"grad",
			"voord",
			"thurn",
			"furt",
			"dorne",
			"wich");
		return q + w;


	}
	Names.tavern		= function(){
		var q = randomOf("The Sleeping ",
				"The Jealous ",
				"The Stinky ",
				"The Drowned ",
				"The Mad ",
				"The Ragged ",
				"The Blind ",
				"The Deaf ",
				"The Angry ",
				"The Saucy ",
				"The Tasty ",
				"The Black ",
				"The Brown ",
				"The Humble ",
				"The Roasted ",
				"The Rusty ",
				"The Old ",
				"The Evil ",
				"The Crazed ",
				"Hell's ",
				"The Black ",
				"The ");
		var w = randomOf("Cat",
				"Weasel",
				"Gull",
				"Hound",
				"Mule",
				"Maiden",
				"Giant",
				"Gnoll",
				"Horseman",
				"Horse",
				"Mare",
				"Huntsman",
				"Hunter",
				"Knight",
				"Lion",
				"Flagon",
				"Badger",
				"Bear",
				"Fox",
				"Raven",
				"Granny",
				"Nun",
				"Rose",
				"Stag",
				"Mage",
				"Priest",
				"Bastard",
				"Prince",
				"Cauldron",
				"Imp");
		var w2 = randomOf("Cat",
				"Weasel",
				"Gull",
				"Hound",
				"Mule",
				"Maiden",
				"Giant",
				"Gnoll",
				"Horseman",
				"Horse",
				"Mare",
				"Huntsman",
				"Hunter",
				"Knight",
				"Lion",
				"Panther",
				"Badger",
				"Bear",
				"Fox",
				"Raven",
				"Granny",
				"Nun",
				"Rose",
				"Stag",
				"Mage",
				"Priest",
				"Bastard",
				"Prince",
				"Cauldron",
				"Imp");
		var e = randomOf("Rest",
			"Perch",
			"Corner",
			"Berth",
			"Lair",
			"Stead",
			"Lodge",
			"Roadhouse",
			"Mill",
			"Alehouse",
			"Hospice",
			"Meadry",
			"Brewery");
		return randomOf(
			q + w, q + w, q + w,
			w + "'s " + e, w + "'s " + e, w + "'s " + e,
			"The " + w + " and the " + w2)
			+ randomOf(
				" Tavern",
				" Inn",
				" Bar",
				"", "", "");
	}
	Names.village			= function(){
		var q = randomOf("High",
				"Hald",
				"River",
				"Lake",
				"Ivern",
				"Dawn",
				"Day",
				"Devil",
				"Maiden",
				"Gold",
				"Merry",
				"Snow",
				"Lumber",
				"Hearth",
				"Amber",
				"Pearl",
				"Opal",
				"Black",
				"Red",
				"Blue",
				"White",
				"Far",
				"West",
				"North",
				"East",
				"South",
				"Dusk",
				"Oak",
				"Belle",
				"Dire",
				"Silver",
				"Shade",
				"Summer",
				"Spring",
				"Fall");
		var w = randomOf("shire",
				"mire",
				"stead",
				"town",
				"'s Cross",
				" Farm",
				"brair",
				"grove",
				"fair",
				"hut",
				"shack",
				"watch",
				"mill",
				"shod",
				"light",
				"wood",
				"'s Retreat",
				"post",
				"side",
				"glen",
				"haven",
				"ridge",
				"shore",
				"field",
				"run",
				"road",
				"cairn",
				"'s Rest",
				"crest",
				"moor",
				"crag",
				"den",
				"rose",
				"'s Shield",
				"fall",
				"dell",
				"pass");
		return q + w;
	}
	Names.water			= function(){
		var q = randomOf("Black",
				"Red",
				"Grey",
				"Blue",
				"Green",
				"Salt",
				"Warm",
				"Cold",
				"Storm",
				"Calm",
				"Summer",
				"Strong",
				"Crag",
				"Stone",
				"Bitter",
				"Rain",
				"Frost",
				"Deep",
				"Still",
				"Murk",
				"Sweet");
		var w = randomOf("water",
				"water",
				"water",
				"water",
				" Bay",
				"lake",
				"sea",
				"sea");
		return q + w;
	}
	Names.world			= function(){
		var q = randomOf(
			"Era",
			"Tera",
			"Qa",
			"War",
			"Eion",
			"Eran",
			"Rea",
			"Tesa",
			"Tas",
			"Yi",
			"Ion",
			"Osh",
			"Per",
			"Az",
			"Ale",
			"Athe",
			"Serte",
			"Sona",
			"Daen",
			"Dal",
			"Fal",
			"Gal",
			"Ga",
			"Garon",
			"Gaer",
			"Hin",
			"Jael",
			"Jaer",
			"Kirin",
			"Drei",
			"Ki",
			"Laon",
			"Leen",
			"Zeta",
			"Xer",
			"Cyn",
			"Ceer",
			"Valir",
			"Valor",
			"Dema",
			"Bael",
			"Nimb",
			"Naeris",
			"Miir",
			"Maer");
		var w = randomOf(
			"ia",
			"thia",
			"rion",
			"sion",
			"ith",
			"eth",
			"ion",
			"eroth",
			"cia",
			"rothen",
			"eris",
			"an",
			"na",
			"sia");
		return q + w;
	}
	Names.zone			= function(){
		var q = randomOf(
			"Mage's ",
			"Warrior's ",
			"Magister's ",
			"The Howling ",
			"The Proving ",
			"Hell's ",
			"The Forgotten ",
			"The Oblivion ",
			"The Stone ",
			"The Eastern ",
			"The Western ",
			"The Northern ",
			"The Southern ",
			"The Searing ",
			"The Screaming ",
			"The Golden ",
			"The Brimstone ",
			"Summoner's ",
			"The Holy ",
			"Sun's ",
			"Moon's ",
			"The Burning ",
			"The Twilight ",
			"The False ",
			"Falcon's ",
			"The Blessed ",
			"The Cursed ",
			"Storm's ");
		var w = randomOf(
			"Retreat",
			"Terrace",
			"Fjord",
			"Grounds",
			"Grave",
			"Pools",
			"Rift",
			"Fields",
			"Kingdoms",
			"Lands",
			"Falls",
			"Wall",
			"Breach",
			"Gate",
			"Gorge",
			"Steppes",
			"Tundra",
			"Abyss",
			"Sea",
			"Hill",
			"Chapel",
			"Altar",
			"Halls",
			"Enclave",
			"Square",
			"End");
	}
	Names.goodOrganization	= function(){
		var q, w;
		q = randomOf(
			"Vigilants",
			"Exemplars",
			"Paragons",
			"Shields",
			"Swords",
			"Knights",
			"Warriors",
			"Hunters",
			"Blazons",
			"Templars",
			"Defenders",
			"Order",
			"Paladins",
			"Alliance");
		w = randomOf(
			"Light",
			"Dawn",
			"the Fire",
			"the Griffin",
			"the Sun",
			"the Moon",
			"the People",
			"the Circle",
			"Dusk");
		return randomOf("", "The ") + q + " of " + w;
	}
	Names.cult 			= function(){
		var q;
		var w;
		q = randomOf(
			"Sect",
			"Cult",
			"Church",
			"Oracles",
			"Creed",
			"Book",
			"Adepts",
			"Initiates",
			"Keepers");
		w = randomOf(
			"Asmodeus",
			"Avandra",
			"Bane",
			"Gruumsh",
			"Lolth",
			"Tharizdun",
			"Tiamat",
			"Torog",
			"Vecna",
			"Zehir",
			"the Dark",
			"the Snake",
			"the Night",
			"Death",
			"Darkness",
			"Doom",
			"Hell",
			"Blood",
			"Dawn",
			"the Unholy",
			"the Damned",
			"the Curse",
			"the Pact");
		return randomOf("", "The ") + q + " of " + w;
	}
	Names.thievesGuild 	= function(){
		var q;
		var w;
		switch(randomInt(1, 7)){
			case 0: q = ""; break;
			case 1: q = "Blue"; break;
			case 2: q = "Black"; break;
			case 3: q = "Night's"; break;
			case 4: q = "Dark"; break;
			case 5: q = "Shadow"; break;
			case 6: q = "Red"; break;
			case 7: q = "Winter's"; break;
			case 8: q = ""; break;
			case 0: q = ""; break;}
		switch(randomInt(1, 15)){
			case 0: w = ""; break;
			case 1: w = "Ravens"; break;
			case 2: w = "Brotherhood"; break;
			case 3: w = "Crows"; break;
			case 4: w = "Guild"; break;
			case 5: w = "Watchers"; break;
			case 6: w = "Legacy"; break;
			case 7: w = "Scouts"; break;
			case 8: w = "Assassins"; break;
			case 9: w = "Dagger"; break;
			case 10: w = "Cloak"; break;
			case 11: w = "Blades"; break;
			case 12: w = "Ghosts"; break;
			case 13: w = "Fantoms"; break;
			case 14: w = "Hand"; break;
			case 15: w = "Alliance"; break;
			case 0: w = ""; break;
			case 0: w = ""; break;
		}
		return randomOf("", "The ") + q + " " + w;
	}

	Names.reggaeSinger = function() {
		let q = randomOf(
			'Jah',
			'Face',
			'Culture',
			'Roots',
			'Masta',
			'Alpha',
			'Dub',
			'Black',
			'Zion',
			'Irie',
			'Steppa',
			'Steppas',
			'Style',
			'Sound',
			'Bush',
			'Bass',
			'Zulu',
			'Lion',
			'Conquering',
			'Dread',
			'Beat',
			'Capital',
			'Soundboy',
			'Riddim',
			'Bredda',
			'Rasta',
			'Rising'
		)
		let w = randomOf(
			'Lion',
			'King',
			'Culture',
			'Roots',
			'Syndicate',
			'Masta',
			'B',
			'Dub',
			'Zion',
			'Foundation',
			'Patrol',
			'Nation',
			'Zone',
			'Steppa',
			'Steppas',
			'Style',
			'Reggae',
			'Vibration',
			'Direction',
			'Dread',
			'Revolution',
			'Army'
		)

		if (q == w) return Names.reggaeSinger()
		else return q + ' ' + w

	}

	Names.voidFaction = function() {
		let q = randomOf(
			'Void',
			'Nether',
			'Hel',
			'Ether',
			'Rever',
			'Under',
			'Dark',
			'Fal',
			'Avar',
			'Eld',
			'Murk',
			'Ebon',
			'Thral',
			'For'
		)
		let w = randomOf(
			'spawn',
			'rim',
			'lings',
			'ren',
			'rant',
			'nant',
			'mer',
			'ner',
			'der',
			'roth',
			'noth',
			'loth',
			'lath',
			'radim',
			'rich',
			'rake',
			'rest',
			'dome',
			'rone',
			'iron',
			'idians',
			'riorn',
			'lorn',
			'riss',
			'kan'
		)
		return randomOf('', 'The ', 'The ') + q + w
	}
